### ISSUE TITLE
Erro ao compilar

### ISSUE THREAD

**Issue by AshKatchup** [MuriloChianfa/TibiaAuto12#1]
Boa tarde!

Como posso compilar o projeto?

Não tenho experiência em Python mas gostaria de analisar o código fonte.

Baixei o PyCharm e ao compilar obtenho o erro "TypeError: _locateAll_python() got an unexpected keyword argument 'confidence'".

Poderia me ajudar?

Email: juvbk.1@gmail.com
WhatsApp: 54-98119-0889

**Comment by MuriloChianfa** [comment]
Boa tarde Amigo...

Para poder compilar o codigo voce necessita de algumas biblioteca instaladas.

Digite o seguinte comando no teminal do seu PyCharm:

pip install PIL
pip install pyautogui
pip install keyboard
pip install pygetwindow

Não tenho certesa... mais acho que são só estas bibliotecas. 
Caso precise de algo me avise. Grande Abraço.

**Comment by AshKatchup** [comment]
Opa, obrigado pelo retorno!

Cara, desculpa a ignorância mas o erro continua (print anexo).

Como eu uso C# no Visual Studio estou apanhando um pouco do PyCharm....

Poderia dar uma olhada?

Pelo que procurei na net, o compilador está executando a função _locateAll_python_ e não a do opencv. Por isso da erro no argumento confidence.




Juvenal Ballista Kleinowski

Advogado - OAB/RS 102.262


________________________________
De: MuriloChianfa <notifications@github.com>
Enviado: domingo, 29 de março de 2020 16:23
Para: MuriloChianfa/TibiaAuto12 <TibiaAuto12@noreply.github.com>
Cc: AshKatchup <juvbk@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [MuriloChianfa/TibiaAuto12] Erro ao compilar (#1)


Boa tarde Amigo...

Para poder compilar o codigo voce necessita de algumas biblioteca instaladas.

Digite o seguinte comando no teminal do seu PyCharm:

pip install PIL
pip install pyautogui
pip install keyboard
pip install pygetwindow

Não tenho certesa... mais acho que são só estas bibliotecas.
Caso precise de algo me avise. Grande Abraço.

**Comment by MuriloChianfa** [comment]
Qual linha que esta dando este erro ?

**Comment by AshKatchup** [comment]
Na "import cv2" (anexo).

So que se eu tento instalar (pip install opencv-python) dá mensagem de que já foi instalado.

Eu preciso referenciar a OPENCV dentro do PyCharm?




Juvenal Ballista Kleinowski

Advogado - OAB/RS 102.262


________________________________
De: MuriloChianfa <notifications@github.com>
Enviado: domingo, 29 de março de 2020 16:48
Para: MuriloChianfa/TibiaAuto12 <TibiaAuto12@noreply.github.com>
Cc: AshKatchup <juvbk@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [MuriloChianfa/TibiaAuto12] Erro ao compilar (#1)


Qual linha que esta dando este erro ?

**Comment by MuriloChianfa** [comment]
pode apagar essa linha, não estou mais usando o openCV... isso era apenas um teste kkk e esqueci de tirar, mais o certo seria ja funcionar caso voce ja tenha instalado o openCV

**Comment by AshKatchup** [comment]
Removi todas referencias ao confidence e agora tudo certo.

Outro probleminha: a função locateOnScreen não está encontrando a imagem EndLocation.png.

Seria o fim da tela (gamewindow)?




Juvenal Ballista Kleinowski

Advogado - OAB/RS 102.262


________________________________
De: MuriloChianfa <notifications@github.com>
Enviado: domingo, 29 de março de 2020 16:55
Para: MuriloChianfa/TibiaAuto12 <TibiaAuto12@noreply.github.com>
Cc: AshKatchup <juvbk@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [MuriloChianfa/TibiaAuto12] Erro ao compilar (#1)


pode apagar essa linha, não estou mais usando o openCV... isso era apenas um teste kkk e esqueci de tirar, mais o certo seria ja funcionar caso voce ja tenha instalado o openCV

**Comment by MuriloChianfa** [comment]
Sim...  `self.button_gw = pyautogui.locateOnScreen("images/PlayerSettings/EndLocation.png", confidence=0.8)`

Provavelmente ele não encontrou esta imagem na sua tela.

**Comment by AshKatchup** [comment]
Tive que tirar print das imagens e fazer as imagens novamente por causa de pequenas diferenças na cor.

Como será que o Oldbot e os demais fazem?


Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by caionakai** [comment]
Oloco, tá ativão o repo

**Comment by MuriloChianfa** [comment]
Esta ativado e pronto pra novas propostas... caso queira ajudar no desenvolvimento de um FORK do repositorio e na medida que voce for programando vc pode fazer os pull requests que eu analisarei com certesa...

@AshKatchup alguns bots atuais quando nao localizam algumas imagens como no seu problema acima, eles pedem para que o usuario selecione a area e tira e print do local, mais tudo de maneira altomatica. Até que é simples implementar isso mais demando tempo pra fazer kkkk

**Comment by caionakai** [comment]
ce usa discord?

**Comment by MuriloChianfa** [comment]
Sim amigo... Light#1555 meu ID, adiciona la.
