### ISSUE TITLE
Contribuir com alguns modulos

### ISSUE THREAD

**Issue by digonalha** [MuriloChianfa/TibiaAuto12#10]
Tenho alguns scripts que utilizo (rune maker, diamond arrow), se eu fizer um fork pra implementar tu da uma olhada no pull request?

**Comment by MuriloChianfa** [comment]
Boa Noite @digonalha . Com certeza olharei com muito prazer...

Qualquer ajuda é bem vinda, o objetivo do BOT é ser feito para a comunidade mesmo.

Desde já agradeço.

**Comment by Matheus-Ribeiro95** [comment]
boa tarde!
aproveitando o tópico, irei dar uma olhada no código e verei no que posso usar também.
parabéns pela iniciativa @MuriloChianfa

**Comment by MuriloChianfa** [comment]
Opa @Matheus-Ribeiro95 Ai sim !! hahaha...

Qualquer duvida sobre o funcionamento ou estrutura, é só perguntar que eu respondo. Vlw Abraços.
