### ISSUE TITLE
Cavebot

### ISSUE THREAD

**Issue by renanperesr** [MuriloChianfa/TibiaAuto12#12]
Olá boa tarde!!! Tudo bem?

Estou com um problema com monster atk, crio uma nova imagem, coloco na pasta, acrescento ele no script, mas não atk o monsto.
No cavebot estou com outra dificuldade, principalmente para criar o script. todas as vezes que eu tento da algum erro ou simplesmente não sai do lugar.

Poderia me ajudar com isso?

**Comment by MuriloChianfa** [comment]
Boa Tarde @renanperesr 

Posso lhe ajudar sim !! Pra adicionar um novo monstro, voce precisa ter a fotinha do nome dele na pasta "Targets"... Depois de adicionar a imagem, você precisar colocar o mesmo nome que você colocou na imagem, no arquivo "Constants.py".

Sobre a questão de andar, eu ainda estou tendo problema com a questão do zoom do mapa kkkk,
eu deixo meu mapa com o zoom assim:

![Alt text](https://i.imgur.com/eHeQDhl.png)

Dai, pra criar um novo script de walking, você coloca algum nome aleatório aqui:

![Alt text](https://i.imgur.com/1EkOTPb.png)

E clica em Load Script... Após clicar, ele vai criar um script vazio, e você pode adicionar novos waypoints selecionando a mark que voce quer clicar em "add":

![Alt text](https://i.imgur.com/lFW4Abc.png)

Quando Você clicar em "add", ele vai adicionar um waypoint, e assim vai indo, por exemplo criei esse script com 2 waypoint:

![Alt text](https://i.imgur.com/h6L7EDv.png)

Dai ele vai ficar andando de uma mark a outra kkkk.
Espero que eu tenha ajudado, se precisar de mais alguma coisa me avise.

**Comment by thunszather** [comment]
boa noite! estou com o mesmo problema, ele nao esta andando, tentei criar um no dp e ate o treiner off e ele nao anda, ai no cmd aparece que nao ta achando o lock (dp)
![image](https://user-images.githubusercontent.com/67078429/85810943-f3844080-b732-11ea-9723-265c6107132a.png)

**Comment by MuriloChianfa** [comment]
Humnm, vou tentar refazer o sistema de marks, mas voce pode tentar alternar o zoom do mapa, tenta diminuir o zoom ou aumentar, para ver se muda alguma coisa.

Se não der, me fale... porque ali no cmd, aparece que ele esta localizando a mark esta vendo.

Narreal, eu acho que sei o que pode ser...
como você esta com 2 telas, você deve setar a tela do Tibia como principal assim:

![Alt text](https://i.imgur.com/xT9rbQB.png)
