### ISSUE TITLE
Erro nas posições

### ISSUE THREAD

**Issue by jrff20** [MuriloChianfa/TibiaAuto12#14]
Quando eu inicio para ele configurar, as posições ficam todas erradas.
No total dão 8 Erros:
Life, Mana, Battle, Statusbar, Map, Player, GameWindow, e Sqmposition.
todas essas posições ele não consegue pegar automaticamente e eu já tentei achar o config manualmente para tentar mudar mas não encontrei.

**Comment by MuriloChianfa** [comment]
Humn... vou tentar dar uma olhada no que pode estar havendo, qualquer coisa lhe retorno, obrigado pelo feedback.

**Comment by anonbrasileiro** [comment]
Alguma notícia?

**Comment by LucasCamboim** [comment]
Também estou com esse problema, Murilo!
Mas observei o trabalho e em teoria está muito bom, grande fã seu desde já.
Se puder, logo mais, gostaria de ter seu contato. Garanto que contribuirei mais do que pedirei.

**Comment by LucasCamboim** [comment]
resolvi este problema hoje mais cedo, percebi que com outras funções ler pixel a tela também estava dando destorcida... Até que percebi que a resolução da tela estava em 125% que é o padrão para hardwares mais novos. Colocando em 100% não houve problema algum em capturar imagems e tela. @MuriloChianfa Se puder coloque no features

**Comment by MuriloChianfa** [comment]
Boa tarde galera, estou meio sem tempo para dar continuidade ao BOT, mas quanto há este problema, não sei o que pode estar acontecendo, lembrando que se vocês estiverem usando 2 telas, coloque a tela em que o tibia e o OBS estão, como a tela principal, talvez seja isso... desculpe-me qualquer coisa.
