### ISSUE TITLE
Alguns erros que encontrei e sujestões.

### ISSUE THREAD

**Issue by johnsilva93** [MuriloChianfa/TibiaAuto12#15]
Olá,
Parabéns cara, seu bot está muito bom! Tenho tendinite e amo jogar Tibia por horas, logo o único jeito de fazer isso é diminuindo ao máximo meus clicks, por isso eu comecei a desenvolver um bot.
Seu bot me ajudou a superar o problema do anti-screenshot do battleeye no meu código, mas ao usar o seu me deparei com alguns problemas:
#1 - Ao rodar o cave bot não é possível parar o script sem fechar a GUI. pois ela trava.
#2 - No meu código eu tenho uma função que verifica se o char ta parado ou andando. Fazendo que não seja necessário definir tempo pra chegar de um waypont a outro( o que da problema quando tem lag).
#3 - Não consegui criar um script de movimento. A GUI trava e não consigo salvar.

fora isso, só queria entender algumas  funções do seu bot. Se poder mandar um contato pra ficar mais fácil de reponder eu agradeço, o nick do discord que você mandou não funciona.

**Comment by MuriloChianfa** [comment]
Fala @johnsilva93 , gostei muito da sua ideia #2 hahahaha.

Meu Discord agora esta assim: Murilo Chianfa#1555

Hora que eu estiver com um tempo livre, tentarei corrigir alguns erros que estao dando 👍
