### ISSUE TITLE
Como colocar o Hook direto no Tibia sem usar o OBS Studio (Para OtServer's)

### ISSUE THREAD

**Issue by GabrielRCL** [MuriloChianfa/TibiaAuto12#17]
como eu posso retirar o hook do OBS Studio e colocar para ele dar Hook diretamente no tibia (para otservers)?

>fui na pasta TibiaAuto12-master\Core\HookWindow.py 
e mudei a linha 
>"hwnd = GetHWND('Windowed Projector')" 
para 
>"hwnd = GetHWND('Tibia -')"

porem ele esta dando erro na hora de pegar as Coordenadas. ele reconhece o Tibia ao invés do OBS mas as coordenadas não estão sendo "hookadas" com exito

**Comment by marquesdaniel** [comment]
Eu fiz isso e funcionou, porém a tela do tibia fica piscando ao usar o bot, devido a alguma função de verifiação de pixel do python, aí tive que voltar pro OBS mas fica pesado =X
