### ISSUE TITLE
Use cavebot for deposit items

### ISSUE THREAD

**Issue by RodrigoAnd3** [MuriloChianfa/TibiaAuto12#19]
Hi, how is the way to deposit the items in the dp?, since the bot looks for the marks on the map, and there is only walk, shovel and rope. Will we need a USE?

**Comment by MuriloChianfa** [comment]
hi, as I was a little out of time to continue developing the BOT, there was no time to deposit items, nor to use shovel and rope ... later I can do it, so we can do some more advanced scripts =)
