### ISSUE TITLE
erro bot

### ISSUE THREAD

**Issue by rafaaagreli** [MuriloChianfa/TibiaAuto12#21]
Estava a realizar alguns testes porem, uma hora ele funcionaval o auto hur e nao funcionava o healling nem o cavebot ficava dando magia para healar sem parar e o cavebot ficava andando em círculos

apos fechar e abrir novamente o auto hur ja nao funcionava mais ficava dando magia sem parar, seria um problema de resolução ?

**Comment by MuriloChianfa** [comment]
oi amigo, acredito que pode ser sua resolução sim!
coloca um print do arquivo Json.json que é o arquivo de configuração pra nos vermos alguns detalhes =)
