### ISSUE TITLE
Tela "piscando"

### ISSUE THREAD

**Issue by marquesdaniel** [MuriloChianfa/TibiaAuto12#22]
Salve mano, tava procurando BOT pra jogar OT 11+, aí encontrei o seu, gostei do projeito, trabalhei um pouco nele pra deixar mais simples, retirei o hook do OBS pois estava pesando, está tudo funcionando porém minha tela fica piscando quando uso ele hookado na tela do tibia, a tela do tibia fica dando uns blinks brancos as vezes quando faz as verificacoes (life. mana, ring, hur, amulet), com autoring e amulet pisca tanto que fica impossivel jogar.... Não sei se é a função takepicture, ou pixel search ou algum bug do python... Vc teria alguma sugestão???
OBS: Hookando o OBS o BOT funciona certinho, mas fica muito pesado pro meu PC...

**Comment by MuriloChianfa** [comment]
Faala marques, eu já sabia desse problema kkkk, o problema é alguma incompatibilidade do hook com o motor gráfico do tíbia.
O que da pra vc fazer, se vc não for deixar ele 100% AFK e ficar em outras coisas, se for só usar como um auxilio pra curar, puxar ring enquanto joga etc... da pra você colocar o pyautogui pra fazer a captura da screen, tavez assim funcione certinho =)
