### ISSUE TITLE
nao consigo abrir o bot

### ISSUE THREAD

**Issue by rafaaagreli** [MuriloChianfa/TibiaAuto12#23]
estou com um problema ao instalar o python e executar os comandos o bot e etc o bot abre porem trava muito a maquina toda sera devido a ser processador amd ?

**Comment by MuriloChianfa** [comment]
boa tarde rafa, pelo que eu entendi, você conseguio abrir o BOT então ?

**Comment by rafaaagreli** [comment]
Murilo eu consegui abrir no note porem o cavebot nao roda de maneira alguma fica dançando...porem o note é fraco decidi testar no computador e agora ele abre ate a parte de dar load nas configs apos feito isso trava todo o computador causando uma lentidão, o meu note é intel e meu pc é amd teria alguma coisa a ver ? porem fui tentar reinstalar o python agora fica dando erro nos comandos para instalar os scripts

**Comment by MuriloChianfa** [comment]
Acho que por o seu computador ser amd não é, pois o meu também é >.<
Mas não sei o porque da lentidão no computador =(
E no not, você lembrou de colocar as marks no mapa para ele seguir ? visto que o problema é que ele fica andando sosinho

**Comment by rafaaagreli** [comment]
sim sim no note fiz tudo certinho porem nao adiantou, ai decidi testar no pc por ser mais forte porem essa lentidão é bizarra kkkkk
nao entendo ele causa a lentidao apos o programa tentar criar o arquivo json

**Comment by MuriloChianfa** [comment]
Humn.. vou tentar dar uma olhada por aqui pra ver se eu acho alguma coisa de errado, qualquer coisa eu lhe reporto =>

**Comment by KazzD** [comment]
aconteceu o mesmo comigo agora e no log do console fica Coping Default Json

**Comment by KazzD** [comment]
fica uma lentidão eterna

**Comment by MuriloChianfa** [comment]
você inicia o bot com o char logado ou ainda sem logar ?

**Comment by MuriloChianfa** [comment]
Tenta dar uma olhada nessa parte do código:

![image](https://user-images.githubusercontent.com/60560085/98719824-fe9cdd80-236e-11eb-9a89-2a92a45906c7.png)

Talvez passar o caminho direto, ou até mesmo, executar o BOT como administrador, vai que ele não esta tendo permissão pra ler o diretório.
Tenta ai e me fala.

**Comment by KazzD** [comment]
Pelo que eu entendi aqui o bot só fica nessa lentidao eterna se for naquela opçao de Otserver
