### ISSUE TITLE
Não acontece nada

### ISSUE THREAD

**Issue by bototonho7** [MuriloChianfa/TibiaAuto12#25]
na parte Choose your config, quando eu clico em create o programa minimiza e nao acontece nada, nao consigo nem voltar ele pra tela principal

**Comment by MuriloChianfa** [comment]
boa noite amigo, o que aparece no log do console ?

**Comment by bototonho7** [comment]
> boa noite amigo, o que aparece no log do console ?

Ja resolvi vlw, so baixei denovo :)
Poderia fazer um tutorial de como usar o cavebot?

**Comment by MuriloChianfa** [comment]
Posso tentar kkk, ele ainda não esta 100% mas da pra dar uma andada e matar uns mobs =>

**Comment by bototonho7** [comment]
> Posso tentar kkk, ele ainda não esta 100% mas da pra dar uma andada e matar uns mobs =>

obg, outra coisa que vc poderia implementar quando der tempo é mais hotkeys pra escolher, como de 0 a 9 e de 0 a 9 com shift e ctrl tbm :)
