### ISSUE TITLE
Having troubles running it

### ISSUE THREAD

**Issue by Asston** [MuriloChianfa/TibiaAuto12#26]
I have followed the instructions, Installed python 3.8 and all of required libs.
I have set up the OBS as described, the OBS window reflecting the Tibia window behind.
Yet i can not start it, when I just open Startbot.py nothing happens. 
When i try to use the command line, here is what i get:
![image](https://user-images.githubusercontent.com/42712879/98522217-b7322680-2274-11eb-8851-0811bcca626b.png)

**Comment by MuriloChianfa** [comment]
did you put this screen ?
![image](https://user-images.githubusercontent.com/60560085/98538124-0f632b80-2269-11eb-93ba-ff8b736e0355.png)

**Comment by Asston** [comment]
Yeah i did
![image](https://user-images.githubusercontent.com/42712879/98559258-adc1b200-22a6-11eb-91bf-98dd80f9f7cc.png)
then i put the window fullscreen behind my tibia client so it is exactly the same
after that i try to open the Startbot.py and i am getting avove error

**Comment by Asston** [comment]
If its needed i can change OBS language to english, but i think you can see from the screenshot that this is the right option

**Comment by MuriloChianfa** [comment]
try to put the name of your window in the program, in the "core" folder, in the "HookWindow.py" file on line 32
![image](https://user-images.githubusercontent.com/60560085/98569844-86acb580-2291-11eb-9786-d160a262983e.png)
![image](https://user-images.githubusercontent.com/60560085/98569892-962bfe80-2291-11eb-8c2c-d4c0527ad39e.png)

**Comment by Asston** [comment]
Hm, I have tried both options: just the begining and full name, but for both scenarios the same error:
![image](https://user-images.githubusercontent.com/42712879/98570897-372bb100-22b4-11eb-9c21-399b5e8c0cea.png)

**Comment by Asston** [comment]
actually i think I will switch the obs to english version, maybe special characters like "ź" and "ł" are the case

**Comment by Asston** [comment]
yup, that was the case 
![image](https://user-images.githubusercontent.com/42712879/98571335-bae59d80-22b4-11eb-997f-b980280b17c4.png)
:D

**Comment by MuriloChianfa** [comment]
opa, agora é só testar o BOT =D
by the way, where are you from?

**Comment by Asston** [comment]
Im from Poland, actually I work as a QA Engineer so yeah I can report u some stuff if I find anything :P
