### ISSUE TITLE
Numpy buga ao tentar abrir o BOT

### ISSUE THREAD

**Issue by KazzD** [MuriloChianfa/TibiaAuto12#28]
eu abro o StartBot.py ele diz alguns erros e fecha o cmd logo em seguida muito rapidamente. consegui tirar um print do cmd antes dele fechar

![image](https://user-images.githubusercontent.com/74263984/98714390-939bd880-2367-11eb-9350-3bebeed66054.png)

**Comment by MuriloChianfa** [comment]
Humnm, me parece ser problema no numpy, você instalou todos os requisitos ?

![image](https://user-images.githubusercontent.com/60560085/98714673-f42b1580-2367-11eb-8b4e-1a2d2cd2ed9b.png)

talvez, tente usar outra versão do numpy

**Comment by KazzD** [comment]
consegui tirar outra print 
![image](https://user-images.githubusercontent.com/74263984/98714934-3fddbf00-2368-11eb-9ae3-aa630a362dd6.png)

**Comment by KazzD** [comment]
o numpy já esta instalado 
![image](https://user-images.githubusercontent.com/74263984/98715023-5a179d00-2368-11eb-8ec8-f521030c6825.png)

**Comment by MuriloChianfa** [comment]
tenta rodar esse comando pra mudar de versao:
pip install numpy==1.19.3

**Comment by KazzD** [comment]
resolveu , mudei a versao pra 1.19.3
![image](https://user-images.githubusercontent.com/74263984/98715396-d7431200-2368-11eb-9943-766876a86362.png)

**Comment by MuriloChianfa** [comment]
eba =DDDDD

**Comment by KazzD** [comment]
obrigado pela ajuda qualquer outro bug eu vou reportar
