### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by emceef94** [MuriloChianfa/TibiaAuto12#29]
Hello,
I was working on a bot of my own and have run in to your project by accident while googling

Do you not encounter the problem of a black screen after a few minutes/5 screenshots? I have tested your method with OBS and its the same for me, the screen is black

**Comment by MuriloChianfa** [comment]
it is precisely because of the black screen that we use OBS, so that we can capture the pixels
=D

**Comment by MuriloChianfa** [comment]
did you manage to run the BOT?

**Comment by emceef94** [comment]
I have not played the game since 2011, so I only heard about battle eye and don't know much about it but blocking screenshots seems like a quite common practice from what I have googled

I did not turn on the bot, since the screen from OBS goes all black after a few minutes, so I get exactly the same effect as when taking regular screenshots either to the disc or to the memory. I have tried changing the graphic engine settings, it made no difference for the screenshot, I have not yet tried it with OBS but I doubt it will change anything

Do you have any clues why OBS works for others and not for me?
