### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by Slizza** [MuriloChianfa/TibiaAuto12#3]
how can i contact you?
i have question regardless your coding skills which could be used in another mmorpg :)

**Comment by MuriloChianfa** [comment]
Iam currently using discord, add me, my id: Light#1555

**Comment by Felipe21** [comment]
im going to add you i have a questin regarding setup. i've supposed to have done everything properly but im getting error at the  cmd console

list index out of range >>> Window Not Located 'Projetor em janela'

C:\Users\felip\Desktop\TibiaAuto12-master>main.py


list index out of range >>> Window Not Located 'Projetor em janela'

C:\Users\felip\Desktop\TibiaAuto12-master>

**Comment by addamprosty** [comment]
Hey Felipe - open HookWindow.py and edit line 23 to contain the name of the preview window - that should work.

**Comment by MuriloChianfa** [comment]
Funcionará, mas o BOT não irá funcionar... pois o BOT usa o OBS pra funcionar. mas agradeço pela preocupação hahahaha.

@addamprosty Gostou do BOT ?
