### ISSUE TITLE
Programa não abre

### ISSUE THREAD

**Issue by haniel-b** [MuriloChianfa/TibiaAuto12#32]
Boa noite, estou com esse problema ao tentar rodar. Ele abre o cmd muito rápido e fecha logo em seguida, mas consegui tirar um print
![image](https://user-images.githubusercontent.com/56046983/100291737-576a9980-2f5d-11eb-90cc-a6b18edc2b22.png)

**Comment by MuriloChianfa** [comment]
Oi, boa noite haniel, ele diz que não conseguiu encontrar o arquivo... talvez pode ser permissão da pasta, tenta rodar ele como Administrador pra ver

**Comment by haniel-b** [comment]
Tentei ir pelo terminal do python executado como admin e agora o erro é 
![image](https://user-images.githubusercontent.com/56046983/100292606-baf5c680-2f5f-11eb-88de-215b0118d1c4.png)

**Comment by MuriloChianfa** [comment]
vishe mano.. agora não sei o que mais pode ser kkkkk

**Comment by MuriloChianfa** [comment]
da primeira vez estava até melhor kkkkkkkk
