### ISSUE TITLE
Ativo?

### ISSUE THREAD

**Issue by lutiqhas** [MuriloChianfa/TibiaAuto12#33]
Murilo, tá ativo nesse projeto ainda mano?
Tentei te stalkear mas vc não responde...
Abraço

**Comment by MuriloChianfa** [comment]
opa, estou aqui kkkk, do que precisa ?

**Comment by lutiqhas** [comment]
Voltei a tentar programar aí quis matar a saudade do projeto preferido. Hahaha

Murilo, tem algum arquivo que substitui o uso do OBS né? 
Como ele capta as informações do Client?
E qual arquivo é esse que não consigo achar? 
Agradeço demais se me tirar essas dúvidas. 
Ah, tou tentando aprender python ainda. Mas me parece que o pyautogui tem um certo delay? Ainda não achei um recurso semelhante que seja bem eficiente.

**Comment by MuriloChianfa** [comment]
Faala irmao, até da pra substituir o OBS, mas só se não usar para o globa...
da pra usar a mesma classe que usa para o OBS, dai é só mudar a janela de captura (o problema é que fica piscando a tela)
ou tambem voce pode usar as outras como pyautogui, PIL, etc...

cada um tem um delay =D agora é só voce testar pra ver qual se encaixa melhor a voce

**Comment by lutiqhas** [comment]
Murilo, eu queria mais é aprender desenvolver mesmo. 
Comecei ler um livro do começo.
Inclusive aceito indicação de livro e material pra estudar. 

Por isso tou procurando a informação lá de em qual module tem as informações de captar o Client sem usar obs. 

Tava pensando em baixar um servidor na máquina e fazer uns testes aqui.
