### ISSUE TITLE
Loot

### ISSUE THREAD

**Issue by glaucio798** [MuriloChianfa/TibiaAuto12#35]
Ola, tudo bem? Paraben pelo bot, muito massa! Não estou conseguindo fazer o char lootear, ele anda, mata mas não looteia. Pode me ajudar?

**Comment by MuriloChianfa** [comment]
opa, boa tarde... então, qual botão do seu tibia esta configurado pra lootear ? talvez possa ser isso

**Comment by glaucio798** [comment]
ta "classic ccontrols" e "loot:right"

**Comment by MuriloChianfa** [comment]
humnnm que estranho, esta certo, agora já não sei o que pode ser kkkk
