### ISSUE TITLE
loot problem coordinates 

### ISSUE THREAD

**Issue by vatxz** [MuriloChianfa/TibiaAuto12#37]
regards :) nice bot

Is there any way to change the coordinates? 
 
I already changed the sizes of the sidesbars but i can't get any loot from corpses because the coordinates always are on the wrong way.

I can attack, but not get loot
I can't attack, but get loot (attacking manually)

**Comment by MuriloChianfa** [comment]
Have a possibility to change a coordinate manually yes, you have to change it in your configuration file

![image](https://user-images.githubusercontent.com/60560085/103483497-64817080-4dc6-11eb-898a-9bbc66b6e886.png)

**Comment by MuriloChianfa** [comment]
These SQM location is the numpad numbers if Im not mistaken

**Comment by vatxz** [comment]
Thanks friend

but now i have another problem, when the bot is looting the clicks are so very fast, doing the looting impossible. Is there a way to put a little time on this task ?


The attacks change every 2 seconds, in lvl 20 being impossible follow an orc spearman 😂😂😂

^ I think the attack time is solved for my self changing the code a little bit
but, i need help with the looting task 


Gracias and have a good day

**Comment by MuriloChianfa** [comment]
I think to add an interval between the clicks, putting a sleep inside this for
![image](https://user-images.githubusercontent.com/60560085/103534748-3eafa680-4e6e-11eb-953f-0e94e666314f.png)

**Comment by vatxz** [comment]
![Uploading 76D3AB0A-4F78-4CE9-AA3E-715B4A0A2063.jpeg…]()

**Comment by vatxz** [comment]
for i, j in zip(range(0, 18, + 2), range(1, 19, + 2)):
            if self.LootButton == 'right':
                self.SendToClient.RightClick(self.SQMs[i], self.SQMs[j])
            elif self.LootButton == 'left':
                self.SendToClient.LeftClick(self.SQMs[i], self.SQMs[j])

            sleep(0.5)

**Comment by vatxz** [comment]
![Sin título](https://user-images.githubusercontent.com/76906734/103657213-3a978d80-4f2f-11eb-9913-a6ea2618895e.png)

**Comment by vatxz** [comment]
https://user-images.githubusercontent.com/76906734/103658461-dd9cd700-4f30-11eb-94ea-ef0a7942576e.mp4

**Comment by MuriloChianfa** [comment]
Great, my friend O.O

Im glad I helped, are you enjoying the bot?

**Comment by vatxz** [comment]
yes, im enjoying the bot, but not playing tibia, enjoying doing a better performance of the bot. 

congratz to you for the bot.

**Comment by vatxz** [comment]
I don't want to annoy you anymore but i want to edit this part, to in the same cave to attack more than 5 monsters, can you tell me where is the repository



![Sin título2](https://user-images.githubusercontent.com/76906734/103660307-1047cf00-4f33-11eb-8aec-7051b15a3e7c.png)

**Comment by vatxz** [comment]
![sss](https://user-images.githubusercontent.com/76906734/103857721-a2a7ba00-507c-11eb-9f66-a0388d3e1f16.png)

to many changes but is working, im  working in the food eater

**Comment by MuriloChianfa** [comment]
its amazing =D

**Comment by tojaszaryczlowiek** [comment]
> ![Sin título](https://user-images.githubusercontent.com/76906734/103657213-3a978d80-4f2f-11eb-9913-a6ea2618895e.png)
> 
> i use this and it works better

What is your mouse mode in tibia and screen resolution? My bot just does not loot, sometimes i see him moving mouse on sqms around my char and that's everything. I see messages saying that i have to go level up to proceed action (???) It is also stopping attack when monster attack me and his battlelist sprite have black frame and starts again when black frame disappear. Should I make his sprite smaller than when it should contain this black attack frame? Also cavebot is walking only to one waypoint and then it gets stuck despite having been added all of them in cavebot. 
@MuriloChianfa what is your screen res? How can i find loot bp xyz?

**Comment by MuriloChianfa** [comment]
this is my mouse option:
![image](https://user-images.githubusercontent.com/60560085/109427719-72bcc900-79d2-11eb-9f27-33008d3aa333.png)

and my resolution:
![image](https://user-images.githubusercontent.com/60560085/109427787-c3ccbd00-79d2-11eb-8b96-88781ca809e5.png)

remembering that if you have more than 1 monitor, the main monitor must be the one that is tibia...
and all settings are saved in the 'newConfig.json' file in the 'scripts' folder, you can modify them at will
![image](https://user-images.githubusercontent.com/60560085/109427866-0ee6d000-79d3-11eb-93ae-8acaa25da104.png)

for loots, it takes the values ​​of the SQM's. they are configured like this:
![image](https://user-images.githubusercontent.com/60560085/109428249-08595800-79d5-11eb-8639-9a43fa5265d4.png)

you can also put them in manually and go testing until you get more accurate!

**Comment by tojaszaryczlowiek** [comment]
Thank you MM, you are very helpful and you made a great work for free which is very unusual in tibia botting community. Thank you!

**Comment by tojaszaryczlowiek** [comment]
Should these coordinates include window and start menu panel or just game window coordinates? If this second thing how did you check their values?

**Comment by MuriloChianfa** [comment]
the eating part is not ready yet, and about him stop attacking the monster, I also don't know why he does it
but im glad you managed to find your coordinates =D
