### ISSUE TITLE
Cavebot Targeting

### ISSUE THREAD

**Issue by CarlosKono** [MuriloChianfa/TibiaAuto12#38]
Boa tarde,

Percebi que o target fica trocando varias vezes, creio que a função IsAttacking / ScannerAttack do Engine/CaveBot/Scanners.py esteja com algum bug.
Fiz um debug e verifiquei que mesmo quando não estava atacando algum monstro o objeto ImagesAttacking ficava em sua maioria "True", mesmo alterando a precisão do algoritmo do opencv ainda estava com o problema.

Outra questão é uma duvida, no CaveBotController.IsAttacking deveria retornar True se ele estivesse atacando algum monstro?

**Comment by MuriloChianfa** [comment]
Infelizmente o cavebot esta com alguns bugs mesmo =(
Mas eu fico feliz que você esteja conseguindo dar uma olhada no codigo :)
lá na função IsAttacking, provavelmente deve ser a precisão errada mesmo, acho que o certo seria até refazer aquilo lá kkkkkk
