### ISSUE TITLE
Waypoints Cavebot e Compatibilidade OS

### ISSUE THREAD

**Issue by CarlosKono** [MuriloChianfa/TibiaAuto12#39]
Bom dia, estou vendo o cavebot e na imagem do Cave Bot Module tem opções por waypoints (X,Y,Z) como é realizado a leitura via memoria? 

A questão de compatibilidade com SO Linux existe? Verifiquei que tem algumas classes para Linux.

**Comment by MuriloChianfa** [comment]
Faala Carlos, bom dia... no cavebot hoje, ele não esta pegando por X Y Z. justamente por não podermos mais ler memória. 
Mas contudo, é possível sim implementarmos um leitura por posição, pegando o mini-mapa do player e fazendo crop no mapa global... quando eu comecei a desenvolver, estava com essa ideia mais dai mudei para os waypoints e acabei esquecendo de mudar as imagens do readme >.<

E sobre a questão do Linux, eu tinha começado a adaptar algumas funções de acordo com as que um amigo aqui da comunidade tinha me passado, mas não acabei continuando =(

**Comment by CarlosKono** [comment]
Entendi, vou ver esta questão do crop do mapa atual e comparar com o mapa global pra obter o x,y,z.

A questão do linux, vou ver se consigo adaptar algumas coisas e fazer rodar.

**Comment by MuriloChianfa** [comment]
ótimo, fico feliz que você possa ajudar =D

**Comment by Kirattus** [comment]
> Entendi, vou ver esta questão do crop do mapa atual e comparar com o mapa global pra obter o x,y,z.
> 
> A questão do linux, vou ver se consigo adaptar algumas coisas e fazer rodar.

Conseguiu colocar pra rodar no linux ?
estava fazendo aqui mas meu código estava dando muito problema, lagando d+ na execução que na hora de healar travava e ele morria sem soltar as proximas heal kkkkk

Vlw

**Comment by CarlosKono** [comment]
> > Entendi, vou ver esta questão do crop do mapa atual e comparar com o mapa global pra obter o x,y,z.
> > A questão do linux, vou ver se consigo adaptar algumas coisas e fazer rodar.
> 
> Conseguiu colocar pra rodar no linux ?
> estava fazendo aqui mas meu código estava dando muito problema, lagando d+ na execução que na hora de healar travava e ele morria sem soltar as proximas heal kkkkk
> 
> Vlw

Ainda não comecei a focar nesta questão.
