### ISSUE TITLE
Loot Option

### ISSUE THREAD

**Issue by ShemmyShem** [MuriloChianfa/TibiaAuto12#40]
Hello :)

I'm trying to see how bot loot from monsters but it just kills and walk.

My bot kills monters but no loot... Is there anything I need to click/add to make it loot ?

**Comment by MuriloChianfa** [comment]
hi, I believe it is the same problem that the other friend went through,
take a look here
https://github.com/MuriloChianfa/TibiaAuto12/issues/37
