### ISSUE TITLE
Cave Bot Issue

### ISSUE THREAD

**Issue by crywolfs** [MuriloChianfa/TibiaAuto12#41]
Hello,

Great work on the bot however the cave bot is not working on Tibia 12.5 OT Server. It constantly print a message that the "Destination is out of range." and "There is no way.", it also doesn't attack monsters even when I am surrounded by them. Any idea what is going off?

![1](https://user-images.githubusercontent.com/22965114/104338002-f63b5d00-54ed-11eb-8a39-b4681d518d15.PNG)
![2](https://user-images.githubusercontent.com/22965114/104338081-0d7a4a80-54ee-11eb-8404-872c31116731.PNG)

**Comment by MuriloChianfa** [comment]
maybe it can be the priority of your screen, do you use more than 1 monitor?

**Comment by crywolfs** [comment]
In this instance I have had my second monitor disconnected from the GPU so I don't think it would be a problem.

**Comment by GODMapper** [comment]
is there any way to solve this?
to make the cavebot work well?

**Comment by rrdicapua** [comment]
Cara, estou tendo o mesmo problema, consegui verificar que se estiver configurado para usar com global, para jogar com a janela em foco ele funciona certinho com o zoom correto, mas as funções que dependem de mouse não funcionam quando configurado para poder utilizar o bot sem a janela em foco (OTSERV mode), tem alguma ideia do que possa fazer para resolver?
