### ISSUE TITLE
From GetHWND.py:  list index out of range

### ISSUE THREAD

**Issue by GODMapper** [MuriloChianfa/TibiaAuto12#42]
![descarga](https://user-images.githubusercontent.com/77310028/105122645-fa96e580-5aac-11eb-9738-1a4d9b5a32da.png)
I'am dont can open the bot I have everything I need installed and configured, could you help me

**Comment by MuriloChianfa** [comment]
this error is because the bot could not find the OBS projector window

**Comment by MuriloChianfa** [comment]
if you use it in another language, that may be the problem!

**Comment by GODMapper** [comment]
I am using it in Spanish
I can help you with testing and ideas, but I know very little about programming, although I learn very quickly.

Could you tell me where I can change the identifier so that I can recognize it in Spanish?

**Comment by GODMapper** [comment]
> if you use it in another language, that may be the problem!

in the English language if it works for me. I will try and see how things are.
![Uploading ingles.png…]()

**Comment by MuriloChianfa** [comment]
are you enjoying the BOT ?

**Comment by GODMapper** [comment]
> im happy for you, are you enjoying the BOT ?

Thanks, sorry for taking a long time to respond, I didn't have internet these 2 days puff .....
I am testing the bot however I am trying to see how to make the targeting and the cave bot work fine since they are not like the demo images XD
I don't know anything about programming but I'm trying to understand how things work to get an idea of how to continue but I don't see how XD
