### ISSUE TITLE
Erro modulo io.py

### ISSUE THREAD

**Issue by hugonh** [MuriloChianfa/TibiaAuto12#43]
Bom dia, não estou conseguindo inicializar

Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\io.py", line 51, in <module>

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

Edit1: Eu não tinha o python3.8.2 instalado e sim outras versões, mas mesmo assim persiste erro

**Comment by MuriloChianfa** [comment]
vishe, nunca vi esse erro O_o

**Comment by MuriloChianfa** [comment]
edai amigo, conseguio resolver o problema ? qualquer coisa podemos entrar no discord para tentarmos ver
