### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by kokosikbol** [MuriloChianfa/TibiaAuto12#46]
Hello im stuck on this, anyone can help?
![Bez tytułu](https://user-images.githubusercontent.com/26489004/109053599-2c6b1f80-76dd-11eb-8117-650351f275b0.jpg)

**Comment by MuriloChianfa** [comment]
good afternoon, maybe write permission on the folder, try to run as administrator.

**Comment by MuriloChianfa** [comment]
if you need, i will send you the script...
