### ISSUE TITLE
HookWindow - "images//tmp_screen.png"

### ISSUE THREAD

**Issue by Kirattus** [MuriloChianfa/TibiaAuto12#47]
Boa tarde!
Na classe Hooker dentro de HookWindow achei referencia de consulta nessa imagem, mas não possui nos arquivos nem referencia de criação no projeto.. pode me ajudar pra que ela serve ?

**Comment by MuriloChianfa** [comment]
opa, edai kirattus...
bomn, fiz quando eu estava portando o bot para rodar em linux tambem, um amigo aqui da comunidade tinha me ajudado mostrando um projeto dele, para eu ter umas ideias, mas acabei deixando de lado... para windows, essa função não server =D

**Comment by Kirattus** [comment]
> opa, edai kirattus...
> bomn, fiz quando eu estava portando o bot para rodar em linux tambem, um amigo aqui da comunidade tinha me ajudado mostrando um projeto dele, para eu ter umas ideias, mas acabei deixando de lado... para windows, essa função não server =D

Opa, ai sim, é pra linux msm que estou reformulando o código, reaproveitando algumas coisas e me deparei com essa parada.
a ideia boa do Linux é o multi desktop em varios monitores (cada usuário com seu mouse/teclado logado na mesma maquina, então caso rode em linux, da pra abrir varios no msm PC limitado apenas as entradas de video do pc)

**Comment by MuriloChianfa** [comment]
eba, fico feliz que queira ajudar, se quiser pode pedir pull, eu aceito de boa =D
