### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by Felipe21** [MuriloChianfa/TibiaAuto12#5]
thanks fo rlrease this and for free i going to test

**Comment by Felipe21** [comment]
help please
list index out of range >>> Window Not Located 'Projetor em janela'

C:\Users\felip\Desktop\TibiaAuto12-master>main.py


list index out of range >>> Window Not Located 'Projetor em janela'

C:\Users\felip\Desktop\TibiaAuto12-master>

**Comment by Felipe21** [comment]
now i get this
C:\Users\felip\Desktop\TibiaAuto12-master>main.py

C:\Users\felip\Desktop\TibiaAuto12-master>
C:\Users\felip\Desktop\TibiaAuto12-master>

**Comment by abrahamfdzg** [comment]
Have you started OBS windowed projector? In my case I've installed OBS Studio with english language, and Tibia Auto is looking for the window "Projetor em janela", it's the same window but in portugues.

**Comment by MuriloChianfa** [comment]
Holy hahahahha, im from brazil, so i put it in portuguese, but today Ill fix this.

**Comment by Felipe21** [comment]
Thanks you guys!

**Comment by Felipe21** [comment]
new errors at start up why could this be happening?
Setting Window Size...

Y GAME WINDOW ERROR
1366 768
Setting Window Size...

Y GAME WINDOW ERROR
1366 768
Setting Window Size...

Y GAME WINDOW ERROR
1366 768
Setting Window Size...

Y GAME WINDOW ERROR
1366 768
Setting Window Size...

**Comment by Felipe21** [comment]
solved i had to enable scalling in OBS BOT IS RUNNING

**Comment by MuriloChianfa** [comment]
did you manage to use the BOT?

**Comment by v900** [comment]
Sim, estão funcionando porém com conflitos, acredito eu da minha tela. No cavebot o mouse passa por cima dos monstros mas não clica neles para atacar. O heal as vezes buga, o Mana heal tmb buga. As config não ficam salvas, ou seja, você poem para atacar corym, da ok, e fecha quando volta está em rat. Acredito que esses erros que dão são por causa de leitura da janela do Tibia, já que modifiquei a imagem do heal no meu e começou a funcionar, porém começou a atropelar outras funções

**Comment by lutiqhas** [comment]
I'm thinking about add mountain troll to test in rook. Any advises? (Starting python student yet)

**Comment by lutiqhas** [comment]
> Sim, estão funcionando porém com conflitos, acredito eu da minha tela. No cavebot o mouse passa por cima dos monstros mas não clica neles para atacar. O heal as vezes buga, o Mana heal tmb buga. As config não ficam salvas, ou seja, você poem para atacar corym, da ok, e fecha quando volta está em rat. Acredito que esses erros que dão são por causa de leitura da janela do Tibia, já que modifiquei a imagem do heal no meu e começou a funcionar, porém começou a atropelar outras funções

Na verdade, pelo meu teste acho que as funções de movimento e ataque deveriam estar separadas. 
Pelo menos aqui a parte da janela parece funcionar bem, mas quando tento desabilitar o movimento e configurar só autoattack ele fica andando aleatoriamente.

**Comment by MuriloChianfa** [comment]
@lutiqhas haa sim, vou dividir o cave bot intao, em attack e walk, se voce quiser colocar o mountain troll, é só adicionar a fotinha do nome dele e colocar o nome no script do modulo de cave bot. vlw abraços.

**Comment by lutiqhas** [comment]
> @lutiqhas haa sim, vou dividir o cave bot intao, em attack e walk, se voce quiser colocar o mountain troll, é só adicionar a fotinha do nome dele e colocar o nome no script do modulo de cave bot. vlw abraços.

Sim, deu pra aprender isso olhando o exemplo que vc deixou s2 (dos stone)

Acho que separar as funções facilita pro bot quanto pra gente mexer.

Uma dúvida, qual mouse preset? Classic control, regular control ou left smart click? (Não conseguir entender só lendo o código)

Inclusive, tenho a impressão de ter usado já algum bot que era possível escolher entre usar teclado ou mouse (ou algo assim, mas faz anos que não jogo)

No caso atual, se eu entendesse essa parte iria facilitar como melhorar a movimentação eu acho.

ah, e vi em algum lugar uma função queue, acho que é o tipo de coisa que facilitaria a tomada de decisões entre walk e attack. Não sei se é pertinente, mas como não pode dá conflito, acho que precisariamos achar algo do gênero.

Tou curioso pra fazer o inject no client e testar isso num server 7.6 que baixei aqui. 

tentando achar um bot em python mais antigo pra mexer nele num otserv offline.

Eu agradeço, aprendendo com este projeto!  (Ou seja, deixa os coment no codigo pra nozes hehe)
abraços!

**Comment by MuriloChianfa** [comment]
Vou começar a comentar mais o código kkk, eu tentei injetar comandos de teclado e mouse no tibia global, mais o client bloqueia todas as requisições, infelizmente kkkk, mais acho que la no bot ele esta clicando com o botão direito se não me engano, meu tibia esta em Classic Contrls e Loot: Right. =)

**Comment by lutiqhas** [comment]
> Vou começar a comentar mais o código kkk, eu tentei injetar comandos de teclado e mouse no tibia global, mais o client bloqueia todas as requisições, infelizmente kkkk, mais acho que la no bot ele esta clicando com o botão direito se não me engano, meu tibia esta em Classic Contrls e Loot: Right. =)

Você tentou em zuna? Battleshield é desativado lá. 
Tem esse code aí pra gente ver?

**Comment by MuriloChianfa** [comment]
Testei em 1 server só, dai já não deu certo, mais pra testa é bem facinho se vc quiser, essa parte tá no arquivo SendToClient.py se quiser dar uma olhada, tanto que em OT da pra usa porque eles não blockam kkkk.

**Comment by lutiqhas** [comment]
> Testei em 1 server só, dai já não deu certo, mais pra testa é bem facinho se vc quiser, essa parte tá no arquivo SendToClient.py se quiser dar uma olhada, tanto que em OT da pra usa porque eles não blockam kkkk.

Tava olhando ele hoje mais cedo. 
Como queria fazer o test num servidor que botei no Pc pra isso, acabei indo ler pra ver se conseguiria mudar a versão. (Instalei o 7.6 pq não achei opções mesmo)

Aí acabei de lá indo atrás dos .py de ataque pra tentar entender os problemas com o mountain troll.
Um deles é que enquanto atacava, ele clickava novamente e recomeçava atacar o mesmo bicho.
Esperava encontrar algo do tipo: 'while attacking wait not attacking' (lol) mas ainda não achei. 
Aí fiquei lendo os códigos e não fui ver ainda a interface, se não mexer nela com cuidado dá algum bug que não entendi. (Acho que não salva algumas coisas que deveriam estar salvas pra continuar rodando)
Se tivesse conseguido, ia fazer algum tipo de slime training, aí já alivia o script pra caso de caçada muito nob. (Rook, Rat, rotworm, white deer...)
Falta aprender quase tudo pra mim, mas tou adorando esse projeto hehehe

**Comment by lutiqhas** [comment]
Funcionando em Zuna sem usar o obs. (mas precisa do obs pra abrir, validar)

tou recebendo o print print("Error1 to locate: " + data[i]["mark"]) da linha 167 do EngineCaveBot.py  da pasta engine. Erro to locate ChechMark, mas o checkmark tá lá. # pra registrar que sou nob.

**Comment by MuriloChianfa** [comment]
Adicionei a opção de salvar as configurações dos módulos hahahahha, agora vou tentar desbugar o atacar, que ele fica clicando no monstro mesmo já estando a atacar ele.

Eu sei onde é o problema,
![Alt text](https://i.imgur.com/AAPq8m6.png)

Quando fui refazer o sistema, fiz a opção da "LocateImage", apenas com o grayscale true hahahahha, por isso ele não acha a borda vermelha do monstro que esta atacando.

Vou tentar arrumar isso, espero que consiga.

**Comment by lutiqhas** [comment]
Mas aí não deu pra adicionar o monstro mudando as configurações em autoattack.py
Antes adicionando na tupla e adicionando as imagens ia. 
Agora quando adiciono, não muda.

**Comment by MuriloChianfa** [comment]
Hmnmnm, qual monstro você está tentando colocar ? falando nisso acho que vou tentar dar uma melhorada no CaveBot, colocar algumas opções novas de attack e tals.

**Comment by lutiqhas** [comment]
Tentei colocar o Troll

**Comment by MuriloChianfa** [comment]
Acho que eu sei porque não deu hahahahha, agora com algumas mudanças que eu fiz, voce tem que adicionar o nome do monstro na lista "Monsters" no arquivo Constants.py em Conf, depois adicionar as fotos de nome no battle e as 2 imagens de attacking... caso não der certo novamente me fale que eu coloco para você.

**Comment by lutiqhas** [comment]
Murilo, faltou o Constants.py, Obrigado! haha
Ainda não testei, o OBS parece que tem vontade própria. Algumas vezes não captura.

**Comment by lutiqhas** [comment]
O único 'erro' que eu percebi até agora é que quando há muitos monstros ele não ataca nenhum. 
Parece que ele demora de atacar, e quando tem 4 ou mais não ataca. Não entendi ainda.
O funcionamento do autoloot não parece regular, não entendi também. (Também pq tem itens que ele precisava deixar pra não carregar peso ou ocupar slot, aí não dei tanta atenção)

**Comment by MuriloChianfa** [comment]
Obrigado pelo feedback @lutiqhas , Quando eu fui testar aqui ele atacava normal com mais de 4 monstros, mais talvez eu posso dar uma regulada a mais.

Sobre essa questão do Autoloot, ele ainda não esta 100% mesmo, as vezes ele não pega o loot quando o monstro morre hahahahaha, tenho que regular isto também.

E também estou pensando em fazer um 'Modulo' para o CustomLoot, mas por enquanto são só ideia hahahahaha, para tira-las do papel leva muito tempo >.<

**Comment by lutiqhas** [comment]
Sim, eu pretendia aprender a construir e mesmo vendo o código é bastante difícil acompanhar. 
CustomLoot é uma boa.
Eu acho que gostaria que ele atacasse assim que o monstro aparecesse na tela. Acho que aumentaria a eficiência.

**Comment by lutiqhas** [comment]
![erro7](https://user-images.githubusercontent.com/66082814/84089471-6bc5d480-a9c5-11ea-9047-37da04369405.png)
Essa Att deu algum erro,

**Comment by MuriloChianfa** [comment]
Nossa eu esqueci de trocar as tuplas hahahahaha, vou comitar aqui denovo, testa ai.

**Comment by MuriloChianfa** [comment]
Estas seguintes imagens ![alt text](https://i.imgur.com/C99SI2d.png)  , estão dando muito problema, qualquer coisa, retirem as fotos do jeito de que esta a tela de vocês.

Eu uso por padrão assim: ![alt text](https://i.imgur.com/4f1Fl2I.png) .

E pra min não da problema, se o de vocês ficar dando erro, tentem mudar para esse estilo.

**Comment by lutiqhas** [comment]
Cara, no olho ali, melhorou bastante o desempenho. Vou deixar um tempo ali pra ver qlqr coisa palpito de novo.
(Já teve um episódio com 5 bichos, demorou uns segundos mas resolveu).

**Comment by MuriloChianfa** [comment]
@lutiqhas Então, eu estava terminando o ThreadManager hoje, é bem dificil hahahaha, mas pelo que eu mexi, já deu uma melhorada....

E o problemas que estava dando ? Resolveu ?

**Comment by lutiqhas** [comment]
> @lutiqhas Então, eu estava terminando o ThreadManager hoje, é bem dificil hahahaha, mas pelo que eu mexi, já deu uma melhorada....
> 
> E o problemas que estava dando ? Resolveu ?

Sim, parece bem mais eficiente. Já deu algumas coisas, como por exemplo dizer que tá atacando e ficar vermelho o bicho mas não atacar.
As vezes leva um puff do monstro e continua andando. Talvez o ideal era pausar o Walker e matar os bichos antes sei lá. (parece complicado)

Agora tá num tilt com os Mark, localiza mas diz que não chegou. (Não sei se faz sentido diminuir a precisão que necessita pra alcançar as Mark) (por um momento algum tempo atrás imaginei que a forma como põe a Mark poderia gerar um float meio difícil de alcançar sei lá)

**Comment by lutiqhas** [comment]
Murilo, você tem tido muitos problemas com OBS?
Pode me falar quais opções que usa no Tibia do options>graphics?
Meu tá: 
Graphics engine: auto select
Antialiasing mode: smoorh retro
Sem fullscreen
Marcado V-sync
Desmarcado no grande rate limit

Será que consigo melhorar o OBS calibrando isso?

**Comment by MuriloChianfa** [comment]
Não estou tendo muitos problemas, mas vou te mostrar o jeito que eu uso !!

![Alt text](https://i.imgur.com/giczfqH.png)

O lado da Esquerda, são as configurações e o lado da Direita, é a tela do Tibia...

**Comment by MuriloChianfa** [comment]
Falando nisso, Eu tentei refazer o CaveBot hoje, pelos meus teste, o desempenho melhorou bastante, o problema é que ele ainda fica parando de attackar o monstro >.< hahahahaha.

Mas com o tempo eu vou melhorando.

**Comment by lutiqhas** [comment]
> Falando nisso, Eu tentei refazer o CaveBot hoje, pelos meus teste, o desempenho melhorou bastante, o problema é que ele ainda fica parando de attackar o monstro >.< hahahahaha.
> 
> Mas com o tempo eu vou melhorando.

Sim, tá bem melhor, mais eficiente e mais rápido. 
As vezes tenho problema nas marks, aí deleto e coloco de novo até funcionar. 
Deu um erro no teste de hoje quando ele pegou loot, não continuou andando e atacando. Mas também eu não consegui conferir direito pq o mouse fechou o obs e virou uma zona.

**Comment by MuriloChianfa** [comment]
As configurações do seu tibia estavam parecidas com as minhas ?

**Comment by lutiqhas** [comment]
> As configurações do seu tibia estavam parecidas com as minhas ?

Não, meu delay teclado tá 250. Botei none em antialiasing, e desativei o showlight effects. 
As duas barras do  das setas tinha configurado conforme você havia dito no Readme pro obs.
Meu hp e mana tá embaixo do set, não do minimap, ainda não vi problema nisso. 



tá aparecendo: you cannot use objects that fast. Pra pegar loot.
Bicho demais ele não ataca.

**Comment by MuriloChianfa** [comment]
Humnmnn... Vou tentar dar um jeito no Loot, e também tentar arrumar o Attack hahahahaha.

Obrigado pelo Feedback.

**Comment by lutiqhas** [comment]
Gostaria de compartilhar essa ideia aqui, 
Da pra configurar o que aparece no battle, então é viável atacar tudo que aparecer no battle?

**Comment by MuriloChianfa** [comment]
Boa ideia @lutiqhas .
Acho que vou pensar em fazer algo do tipo.

**Comment by addamprosty** [comment]
Hey, I'm getting stuck on this stage (after fixing the OBS hook caused by different language:

C:\Users\AdamParker>"C:\Users\AdamParker\AppData\Local\Programs\Python\Python38-32\Scripts\TibiaAuto12-master\Main.py"
>>> OBS's Window Located
[33mStart in 1 Seconds...
Traceback (most recent call last):
  File "C:\Users\AdamParker\AppData\Local\Programs\Python\Python38-32\Scripts\TibiaAuto12-master\Main.py", line 9, in <module>
    main()
  File "C:\Users\AdamParker\AppData\Local\Programs\Python\Python38-32\Scripts\TibiaAuto12-master\Main.py", line 5, in main
    WindowSelectCharacter()
  File "C:\Users\AdamParker\AppData\Local\Programs\Python\Python38-32\Scripts\TibiaAuto12-master\Modules\__init__.py", line 118, in WindowSelectCharacter
    with open('Scripts/Loads.json', 'r') as LoadsJson:
FileNotFoundError: [Errno 2] No such file or directory: 'Scripts/Loads.json'

Any clue how to fix that?

**Comment by MuriloChianfa** [comment]
@addamprosty Good afternoon friend, how are you running BOT?

One tip is that you don't need to put it in the python folder.

You can also run it normally by clicking on the "Main.py" file that it will already open the BOT normally.

If it doesn't work, send another message.

**Comment by addamprosty** [comment]
Okay, running direclty from main.py allowed to start the bot. Autoheal doesn't seem to read the health bar position, as it sends strong heal hotkey even at 100% health

**Comment by MuriloChianfa** [comment]
Try to reconfigure the positions ...

When you start the bot, click on the "Reconfigure" button, I think it may be something that he did not set right.

Remember to place the OBS projector identical to Tibia.

**Comment by Shejker** [comment]
Well, i don't wanna to make another topic, but - is someone has a working script for Salamander Cave? I'm getting annoyed with making script by my own. If someone has a working script or scripts for knight at FACC please ping me - we can make a deal ($$/TC/GP).

**Comment by GODMapper** [comment]
> Well, i don't wanna to make another topic, but - is someone has a working script for Salamander Cave? I'm getting annoyed with making script by my own. If someone has a working script or scripts for knight at FACC please ping me - we can make a deal ($$/TC/GP).

contact me at the discord I think I can help you
Arsheria Mapper#3983

**Comment by MuriloChianfa** [comment]
great suggestion, I'll add it to the suggestion board so we can make more scripts

**Comment by kmex** [comment]
sou novo aqui, estou apanhando pra começar o programa. 
erro de battleposition
start.py
Start in 1 Seconds...

Your Configure Stats: False
Coping Default Json

Health Location [X: 1902 Y: 288]

Mana Location [X: 1906 Y: 202]

Battle Position Error

Status Bar Start [X: 1753, Y: 264]
Status Bar End [X: 1858, Y: 274]

Ring's Square Start [X: 1753, Y: 206]
Ring's Square End [X: 1784, Y: 237]

Amulet's Square Start [X: 1753, Y: 134]
Amulet's Square End [X: 1784, Y: 165]

MiniMap Start [X: 1753, Y: 5]
MiniMap End [X: 1858, Y: 113]

Size of MiniMap [X: 105, Y: 108]

Player Position [X: 872, Y: 405]

Game Window Start [X: 1, Y: 2]
Game Window End [X: 1744, Y: 809]

Size of Your SQM [Width: 116px, Height: 73px]

1° SQM Location [X: 756, Y: 478]
2° SQM Location [X: 872, Y: 478]
3° SQM Location [X: 988, Y: 478]
4° SQM Location [X: 756, Y: 405]
5° SQM Location [X: 872, Y: 405]
6° SQM Location [X: 988, Y: 405]
7° SQM Location [X: 756, Y: 332]
8° SQM Location [X: 872, Y: 332]
9° SQM Location [X: 988, Y: 332]

Some Errors Occurred... Opening The Manual Config.
Unfortunately, You Will Have To Manually Configure The Following Errors:

Error[1] = BattlePosition

**Comment by MarceloShibutani** [comment]
Salve galera, alguem ja fez algum video tutorial? 
sou meio leigo nisso, só consegui instalar as lib, travei aqui
