### ISSUE TITLE
running out of memory

### ISSUE THREAD

**Issue by tojaszaryczlowiek** [MuriloChianfa/TibiaAuto12#50]
Okay, so i've encountered some problem about stability. Sometimes when i run any module my system is slowing down so badly it is not possible to open any window and mouse is lagging. All i can to is to reset system. I've given more virtual memory but it didn't help much. Obs on it's own isn't draining much of memory but running bot is draining it. Any idea on how to fix it? I have 8 Gbs of ram and 4gb of gpu ram, should i add more?

**Comment by MuriloChianfa** [comment]
humnm, I think it's a bug ... normally it doesn't consume that much memory!

for example:
![image](https://user-images.githubusercontent.com/60560085/109422206-582a2600-79b9-11eb-9a2f-3f5e9ad22307.png)

**Comment by MuriloChianfa** [comment]
try change your python version ... use 3.7 maybe
