### ISSUE TITLE
Murilo me ajude, tenho windows 7..

### ISSUE THREAD

**Issue by unblind7** [MuriloChianfa/TibiaAuto12#51]
oii tenho windows 7 como instala passo a passo me ajude por favor..
qual seu email ou discord! tibia auto nao to conseguindo aqui...

**Comment by MuriloChianfa** [comment]
oi, se eu não me engano, o processo de instalação é o mesmo =D
meu discord caso queira conversar: Murilo Chianfa#1555

**Comment by unblind7** [comment]
ok vou te add..

**Comment by jvgasparoni** [comment]
Murilo me adiciona, to precisando falar com tu Halt#4219

**Comment by jvgasparoni** [comment]
> oi, se eu não me engano, o processo de instalação é o mesmo =D meu discord caso queira conversar: Murilo Chianfa#1555

Murilo me adiciona, to precisando falar com tu Halt#4219
