### ISSUE TITLE
Bot não funciona no windows 10

### ISSUE THREAD

**Issue by reginaldosanto** [MuriloChianfa/TibiaAuto12#52]
Estou com problema para executar o bot, alguem pode me ajudar?
Instalei todos prerrequisitos, mesmo assim não funciona.
![Capturar](https://user-images.githubusercontent.com/79871482/109549985-7709e480-7aad-11eb-8914-fea5554f9c09.PNG)

**Comment by MuriloChianfa** [comment]
ué kkk mas que print é esse ?

**Comment by reginaldosanto** [comment]
Coloquei a correta, foi mals.
