### ISSUE TITLE
Iniciar sem OBS direto no otserv

### ISSUE THREAD

**Issue by plutospiel** [MuriloChianfa/TibiaAuto12#54]
Boa noite Murilo, antes de qualquer coisa, parabens pelo projeto, utilizo win10 pro 64bits, instalei tudo do python porém o StartBot.py não inicia, até abre um prompt quando tentei abrir direto pelo arquivo, pelo cmd tentei das 2 formas, executando no prompt e executando no prompt do python, a dúvida é se esse projeto só funciona no OBS, eu jogo um otzinho maroto 12.6 e queria tentar mas não tive sucesso, tem alguma dica de solução?

**Comment by MuriloChianfa** [comment]
Acabei de tirar a dependência do OBS, agora dá pra capturar direto a screen do OTServer
