### ISSUE TITLE
how can i solve this 

### ISSUE THREAD

**Issue by bravoxes** [MuriloChianfa/TibiaAuto12#56]
i meet this one and i can't solve it 
![2021-03-16_041645](https://user-images.githubusercontent.com/80731363/111246215-8a20c680-860e-11eb-9011-b73c4db202c7.png)

**Comment by bravoxes** [comment]
tried many times and i got this one too
![2021-03-16_042529](https://user-images.githubusercontent.com/80731363/111246865-b5f07c00-860f-11eb-9d38-d2a6dbf65d1f.png)

**Comment by monsivaisz** [comment]
can the owner please help up with this...

**Comment by MahmoudAshrafMahmoud** [comment]
@MuriloChianfa  i think something is wrong with the images comparing, i started having the same issue too
