### ISSUE TITLE
Não inicializa

### ISSUE THREAD

**Issue by revernus** [MuriloChianfa/TibiaAuto12#57]
Todos os requerimentos foram instalados com sucesso. Quando eu tento inicializar, aparece uma mensagem de erro e finaliza. Uso Windows 10, está atualizado e o cliente do Tibia é a última versão também. Alguma ideia do que pode estar acontecendo?

(Obs: postei o código inicialmente, mas ficou com formatação bizarra, então editei colocando um print do código)
![image](https://user-images.githubusercontent.com/6760061/111355338-072b5a80-8666-11eb-8fb9-51cc7586559c.png)

**Comment by MuriloChianfa** [comment]
boa tarde, isso é apenas porque você não está com o OBS configurado...

**Comment by kamahall** [comment]
> boa tarde, isso é apenas porque você não está com o OBS configurado...

bro buenas noches, como configuro OBS?
