### ISSUE TITLE
Problema ao ler o OBS ?

### ISSUE THREAD

**Issue by Nakombi13** [MuriloChianfa/TibiaAuto12#58]
Quando eu clico em create na janela de choose your config, não acontece nada, o bot fica travado e não abre a janela do menu do bot. Também não da pra abrir o console ele minimiza imediatamente e volta pra janela do OBS. Olhando o console pela funcionalidade do windows 10 aparece "Your Configure Stats: False" e também "Coping Default Json". Sabe oque poderia ser? Já estou com o OBS em modo janela do mesmo tamanho do tibia.
![image](https://user-images.githubusercontent.com/80857928/111541750-9fe9d500-874f-11eb-9022-3008c8737d5e.png)

**Comment by Nakombi13** [comment]
E quando funciona, o autoheal fica assim ele diz que usou o F1 mas no jogo ele não usa.
![image](https://user-images.githubusercontent.com/80857928/111545852-7d5aba80-8755-11eb-86a6-b9d31f10b61c.png)

**Comment by MuriloChianfa** [comment]
oi, boa noite, se você usar mais de 1 monitor, ele tem que ser o principal, e a tela do tibia deve estar afrente para ele poder clicar =D

**Comment by Nakombi13** [comment]
Obrigado pela resposta, eu uso apenas um monitor com a tela do tibia afrente da tela do OBS, e mesmo assim ele não faz nada no jogo, apenas aparece isso "pressed f1"... Poderia ter uma ideia do que seja?

**Comment by Nakombi13** [comment]
Resolução talvez?

**Comment by MuriloChianfa** [comment]
acho que a resolução não é, você vai ter que fazer alguns testes com o python pra ver o que pode ser...
