### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kamahall** [MuriloChianfa/TibiaAuto12#59]
good night brother I added you to the discord, can you help me with this? 
![ERRO](https://user-images.githubusercontent.com/80880451/111596795-ebc66980-87a3-11eb-9695-745efa8d1be5.png)

**Comment by MuriloChianfa** [comment]
you just need to configure OBS = D

**Comment by GandiiPL** [comment]
> you just need to configure OBS = D

I have the same problem as author of this post.

TibiaAuto 12 is working on my PC, but it's not working on my laptop - the same "Window Not Located" problem.

But, which is funny, I have the same Tibia and OBS settings on both PC and laptop.
So I don't understand how it works on PC and doesn't works on laptop...

**Comment by GandiiPL** [comment]
Nevermind, I fixed the problem. 

Please pin the information that the system language must be set to English.

I had my language set (Polish) and that's why it couldn't find OBS window.
