### ISSUE TITLE
Remove dependency on OBS Studio

### ISSUE THREAD

**Issue by abrahamfdzg** [MuriloChianfa/TibiaAuto12#6]
I'm aware of the battleye protection against screenshots, and that is why you are using ODS Studio, but not all users will be able to setup all of this. 

I think there could be a way to get around this. Using the Dwm api DwmRegisterThumbnail you receive a thumbnail of a window that is renderer on top of another window. You cannot take screenshots directly but I believe that there is a way to make this work.
[https://docs.microsoft.com/en-us/windows/win32/dwm/thumbnail-ovw](DwmRegisterThumbnail)

I didn't deep into the topic but here could be some helpful links:
[https://github.com/factormystic/FMUtils.Screenshot/blob/master/Screenshot.cs](Some code in C# that i think is doing this)

Haven't tested anything on this, but I'll try to have some examples for this week.

Greets

**Comment by abrahamfdzg** [comment]
Nop, It wasn't as easy as I thought, the Battleye somehow make the thumbnail black as well.

**Comment by MuriloChianfa** [comment]
yeah, thats why Im using OBS hahahahaha

**Comment by MuriloChianfa** [comment]
I tried to go through Tibias BlackScreen, but with OBS it was the only way.

**Comment by MuriloChianfa** [comment]
now i'm studying the OBS code, to be able to see how it works, so we can make our own "API". But its is a very hard, hahahahha, take a look https://github.com/obsproject/obs-studio and https://obsproject.com/docs/

**Comment by abrahamfdzg** [comment]
Yeah I tought that as well, later on night I will deep into the code but as far as I've seen the function that we want is into libobs-winrt/winrt-capture.cpp in winrt_capture_init function .

**Comment by MuriloChianfa** [comment]
I was thinking about it, then ill ask some forums if anyone knows more about it.

**Comment by MuriloChianfa** [comment]
that would be good, as the BOT is a bit heavy to run.

**Comment by emceef94** [comment]
Hi,
this is the best answer that I found, probably  you have also seen it

https://www.unknowncheats.me/forum/anti-cheat-bypass/383217-injection-using-video-capture-software.html

**Comment by MuriloChianfa** [comment]
Precisely why we use OBS, because it has a dll compiled with certificate, so tibia cannot ban, if we did ours we could be caught and banned.

With OBS it is 100% safe =)

**Comment by emceef94** [comment]
Hello,
unfortunately this solution allows only 1 bot and is resource consuming
I am not good with programming/IT to understand how to get the certificate or how it is checked, but is it possible to do this somehow in a bot without getting caught?

**Comment by MuriloChianfa** [comment]
I think it would be possible, but i dont know how to do that either, hahahaha

There would have to be a very low level of programming, I am also not very good at doing this =(

**Comment by Felipe21** [comment]
if i run this in linux it will posible to get rid of obs?  linux doe snot have battleeye it doesnt work in there and you can directly read the pixels from game

**Comment by Roger-a-Silva** [comment]
I already tryed it on linux.
After some minutes, it became unable to read directly from the game

**Comment by MuriloChianfa** [comment]
great suggestion, I'll add it to the suggestion board so we can integrate the BOT with linux kernel
