### ISSUE TITLE
como instalo o bot no windows 10 sem dar erro

### ISSUE THREAD

**Issue by demonlokai** [MuriloChianfa/TibiaAuto12#60]
tentei instalar o bot no windows 10 mais da erro ao executar o arquivo .py

**Comment by demonlokai** [comment]
por favor  me responda

**Comment by demonlokai** [comment]
o bot tem algum exe?

**Comment by MuriloChianfa** [comment]
não tem EXE, teste abrir seu terminal em modo de administrador e executar o bot por ele pra ver o erro que da...

**Comment by MuriloChianfa** [comment]
se o seu python não estiver na PATH, você pode executar o BOT assim:
![image](https://user-images.githubusercontent.com/60560085/112367481-b8f70680-8cb8-11eb-8acf-79ba42e4e229.png)

**Comment by demonlokai** [comment]
deu esse erro:não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

**Comment by MuriloChianfa** [comment]
tira uma print pra nós vermos = D

**Comment by demonlokai** [comment]
![image](https://user-images.githubusercontent.com/56772117/112380838-a1277e80-8cc8-11eb-96ed-4336ee2a612d.png)

**Comment by MuriloChianfa** [comment]
o problema está no espaço no nome do seu usuario, "Tiago Jucá", tente colocar após o Tiago, o signal de: ^
EX: Tiago^ Jucá

**Comment by MuriloChianfa** [comment]
ou talvez envolver o comando do python, com aspas ""

**Comment by demonlokai** [comment]
nem um desses que vc falou funcionou e como executor o StartBot.py no python da isso:
![image](https://user-images.githubusercontent.com/56772117/112382008-0f207580-8cca-11eb-8ef2-0fb04809f630.png)

**Comment by MuriloChianfa** [comment]
que estranho, o meu funciona '-' 
![image](https://user-images.githubusercontent.com/60560085/112382519-b7ced500-8cca-11eb-97ef-2c6642817a91.png)

**Comment by MuriloChianfa** [comment]
você está fazendo alguma coisa de errado kkk

**Comment by demonlokai** [comment]
manda o codigo que tenho executar aqui

**Comment by demonlokai** [comment]
se possivel

**Comment by MuriloChianfa** [comment]
como administrador, abre o terminal
depois, executa 1 de cada vez:

cd C:\Users\Tiago Jucá\Desktop\TibiaAuto12-master
"C:\Users\Tiago Jucá\AppData\Local\Programs\Python\Python39\python.exe" StartBot.py

**Comment by MuriloChianfa** [comment]
vamos ver se vai dar assim

**Comment by MuriloChianfa** [comment]
ou simplesmente se você tiver o python no seu PATH

cd C:\Users\Tiago Jucá\Desktop\TibiaAuto12-master
python StartBot.py

**Comment by demonlokai** [comment]
![image](https://user-images.githubusercontent.com/56772117/112383505-f3b66a00-8ccb-11eb-83a3-5b4a0acc29bc.png)

**Comment by MuriloChianfa** [comment]
meu amigo.. você nem instalou as dependencias ainda ? '-'

**Comment by demonlokai** [comment]
acho que sim

**Comment by demonlokai** [comment]
como faz

**Comment by MuriloChianfa** [comment]
de dentro da pasta do BOT com o terminal, executa:

pip install requirements.txt

**Comment by demonlokai** [comment]
![image](https://user-images.githubusercontent.com/56772117/112384301-ffeef700-8ccc-11eb-9709-39719c22bbe9.png)

**Comment by MuriloChianfa** [comment]
opa, me desculpe kkk faltou o -r

pip install -r requirements.txt

**Comment by demonlokai** [comment]
instalou uns negocio e apaceu isso : 
![image](https://user-images.githubusercontent.com/56772117/112384762-8d324b80-8ccd-11eb-87a4-87d6ba69f4e4.png)

**Comment by MuriloChianfa** [comment]
vishe, agora complicou, nunca vi isso

**Comment by demonlokai** [comment]
nem eu

**Comment by MuriloChianfa** [comment]
você vai ter que pesquisar no google pra ver o que é que pode estar acontecendo.

**Comment by demonlokai** [comment]
Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1: da esse erro e nao tem no google

**Comment by demonlokai** [comment]
bug do demonio

**Comment by demonlokai** [comment]
esse bot roda em linux? se roda da pra fazer em maquina virtual?

**Comment by MuriloChianfa** [comment]
infelizmente, o tibia não roda mais em maquina virtual =( 
e tambem o BOT ainda não tem suporte pra linux

**Comment by demonlokai** [comment]
a entendi é que eu ia usa em otserv

**Comment by demonlokai** [comment]
mano reistalei tudo e consegui roda te amo s2

**Comment by demonlokai** [comment]
oque é BUTTON GAME WINDOWS IS NONE
