### ISSUE TITLE
AutoMana wrong comparrision

### ISSUE THREAD

**Issue by JanSteffes** [MuriloChianfa/TibiaAuto12#61]
In the automana module, values are compared like this:
```
if ManaCheckStageTwo.get():
    stage_two = ManaPercentageStageTwo.get()   
    if stage_two > Mana or stage_two == Mana:
        ...
elif ManaCheckStageOne.get():
    stage_one = ManaPercentageStageOne.get()
    if stage_one > Mana or stage_one == Mana:
        ...
```

in a test of mine with full mana, these compares never worked out, since Mana was always greater than stage_two / stage_one (in my case 70).

Shouldn't that compare be the over way around? If mana is higher than stage_two / stage_one instead of the current way?

```
if ManaCheckStageTwo.get():
    stage_two = ManaPercentageStageTwo.get()   
    if Mana > stage_two or stage_two == Mana:
        ...
elif ManaCheckStageOne.get():
    stage_one = ManaPercentageStageOne.get()
    if Mana > stage_one or stage_one == Mana:
        ...
```

**Comment by MuriloChianfa** [comment]
hello jan, i didnt understand very well why this inversion in the comparison ... because in my tests it didnt work as it should =/

**Comment by JanSteffes** [comment]
in my it didn't.
Let's say your char has full mana and the stage one / two percentage is set to 70.
The previous comparission won't ever fulfill since mana 100 is greater than 70.

But maybe i didn't get the intention behind the current comparission. As i tried it out with my char, the condition never fulfilled since Mana as 100.

**Comment by MuriloChianfa** [comment]
maybe it didnt get the right position, you can test it, seeing the color of the pixel its taking ... the pattern of the colors, its what is predefined in the file “Constants.py”

**Comment by JanSteffes** [comment]
With the current code, modified with some outputs 

```
print('automana is ', Mana)
if Mana is None:
    Mana = 0

if ManaCheckStageTwo.get():
    stage_two = ManaPercentageStageTwo.get()
    print('stage two is ', stage_two)
    if stage_two > Mana or stage_two == Mana:
        self.SendToClient.Press(ManaHotkeyStageTwo.get())
        print("Pressed ", ManaHotkeyStageTwo.get())
elif ManaCheckStageOne.get():
    stage_one = ManaPercentageStageOne.get()
    print('stage one is ', stage_one)
    if stage_one > Mana or stage_one == Mana:
        self.SendToClient.Press(ManaHotkeyStageOne.get())
        print("Pressed ", ManaHotkeyStageOne.get())
else:
    print("Modulo Not Configured")`
```

i get this while having full mana:

```
automana is  100
stage one is  85
automana is  100
stage one is  85
automana is  100
stage one is  85
automana is  100
stage one is  85
```

the "Pressed" print is never done, since the condition stage_two > Mana won't ever be fulfilled.

With changing the comparission as in the pr, i get this:
```
automana is  100
stage one is  85
Pressed  F3
automana is  75
stage one is  85
automana is  85
stage one is  85
Pressed  F3
automana is  75
stage one is  85
automana is  85
stage one is  85
Pressed  F3
automana is  75
stage one is  85
```

since the condition fulfilled


in my case it seems like it can read the correct values, since automana seems to be read correctly.


But may give me a hint here, is _Mana_ meant to be the current filled % of mana? So if my chars has 155 mana max and is currently at that, _Mana_ should be 100, and everything below respectivly less, or am i mistaken on that?

**Comment by MuriloChianfa** [comment]
the variable "Mana", is the percentage of your current mana, if it is below or equal to what you defined in the BOT, it will press the button to heal.

example:
I set it so that my mana is healed below 70% with the F3 button, I used the "exori gran" to spend mana and it healed normally: 

![image](https://user-images.githubusercontent.com/60560085/112758235-99672300-8fc3-11eb-9d35-6f75371f60e6.png)

**Comment by MuriloChianfa** [comment]
you can debug it to see how its pixel color is, mine is detecting like this: 

![image](https://user-images.githubusercontent.com/60560085/112758305-02e73180-8fc4-11eb-86c5-8d849ce66a15.png)

and compare with the colors in "Constants.py": 

![image](https://user-images.githubusercontent.com/60560085/112758327-24e0b400-8fc4-11eb-8cec-b9130fe36ce3.png)

he is constantly checking if the "70%" (for example) is equal to the color defined in "ManaColor", if different, he heals = D

**Comment by JanSteffes** [comment]
ohh wait, i think i understand, i misstook the automana for autospell, i guess that's what this is about.

Sorry for that :D i guess i'll close the issue and pullrequest
