### ISSUE TITLE
Entrando e saindo do combate e não pega loot

### ISSUE THREAD

**Issue by ShadowsZD** [MuriloChianfa/TibiaAuto12#63]
Estou com 2 problemas ao usar o cavebot.

O primeiro é que apesar de encontrar o target, o bot acaba selecionando ele várias vezes, alternando entre atacar e ficar parado, tenho que mudar algo para que ele deixe selecionado até matar?

O segundo ponto é que ele não pega o loot após matar os mobs, o que posso fazer para que ele colete o loot?

Outra dúvida é, tem como deixar o bot rodando sem estar com a tela do jogo selecionada? Quando faço isso ele continua clicando na tela que estou utilizando.

Valeu!

**Comment by thiagobordoni** [comment]
Conseguiu resolver? quanto a tela acredito que não tem jeito, é deixar com ela visível mesmo. Agora quanto a atacar os bichos, ele fica clicando a cada hit, não fica "clicado" até matar e também não consigo configurar a coleta do loot.

**Comment by SolwynCa** [comment]
Estou tendo os mesmos problemas que vc. O looter roda muito rápido e acaba não pegando nada
