### ISSUE TITLE
ThreadManager

### ISSUE THREAD

**Issue by Kirattus** [MuriloChianfa/TibiaAuto12#65]
Iae jovem, estou aproveitando bastante código do seu projeto para rodar em Linux ( muda muita coisa por conta das dll exclusivas do windows)
Sei que as vezes é chato essas perguntas mas....
sua classe ThreadManager.py esta funcionando corretamente para pausar os thread? vi q esta implementada mas no meu código não funcionou corretamente para "Pausar" os thread em execução mesmo seguindo o guia de comentário.
Se puder dar uma ajuda, ate compartilho o projeto, como estou "Brincando" com o python por hobby, esta dificil compreender o codigo haha ( programação por hobbie msm)
"PrintScreen" é o método responsável por tirar print da tela

![ae](https://user-images.githubusercontent.com/34078319/116941957-07e47400-ac47-11eb-88b3-122659a4ebf9.png)

**Comment by MuriloChianfa** [comment]
oi amigo, pelo que eu me lembro, estava funcionando sim, vou testar aqui
mas essa classe estava meio bugada mesmo kkkkkk

**Comment by MuriloChianfa** [comment]
realmente, não está pausando kkkkkkk

**Comment by Kirattus** [comment]
tive q colocar um boleano na classe pra finalizar, e depois criar de novo, vou tentar ver uma solução, se funcionar no seu projeto eu solicito pull pra te enviar kkk vlwwws

**Comment by yurisbv** [comment]
> Iae jovem, estou aproveitando bastante código do seu projeto para rodar em Linux ( muda muita coisa por conta das dll exclusivas do windows)
> Sei que as vezes é chato essas perguntas mas....
> sua classe ThreadManager.py esta funcionando corretamente para pausar os thread? vi q esta implementada mas no meu código não funcionou corretamente para "Pausar" os thread em execução mesmo seguindo o guia de comentário.
> Se puder dar uma ajuda, ate compartilho o projeto, como estou "Brincando" com o python por hobby, esta dificil compreender o codigo haha ( programação por hobbie msm)
> "PrintScreen" é o método responsável por tirar print da tela
> 
> ![ae](https://user-images.githubusercontent.com/34078319/116941957-07e47400-ac47-11eb-88b3-122659a4ebf9.png)

Amigo você fazer um fork pra o linux, pode compartilhar comigo? Abraços!

**Comment by Kirattus** [comment]
> > Iae jovem, estou aproveitando bastante código do seu projeto para rodar em Linux ( muda muita coisa por conta das dll exclusivas do windows)
> > Sei que as vezes é chato essas perguntas mas....
> > sua classe ThreadManager.py esta funcionando corretamente para pausar os thread? vi q esta implementada mas no meu código não funcionou corretamente para "Pausar" os thread em execução mesmo seguindo o guia de comentário.
> > Se puder dar uma ajuda, ate compartilho o projeto, como estou "Brincando" com o python por hobby, esta dificil compreender o codigo haha ( programação por hobbie msm)
> > "PrintScreen" é o método responsável por tirar print da tela
> > ![ae](https://user-images.githubusercontent.com/34078319/116941957-07e47400-ac47-11eb-88b3-122659a4ebf9.png)
> 
> Amigo você fazer um fork pra o linux, pode compartilhar comigo? Abraços!

Posso te passar o projeto base, mas o fork não vai funcionar pq meu projeto está bem diferente.. 
Ainda n tem nada funcionando.. meu filho nasceu e n tô com tempo.. fiz só as classes de interação com Tibia(use, look, open, goto, etc), pegar layout do jogo, mas nada automatizado ainda... Depois vou te mandar privado

**Comment by yurisbv** [comment]
> > > Iae jovem, estou aproveitando bastante código do seu projeto para rodar em Linux ( muda muita coisa por conta das dll exclusivas do windows)
> > > Sei que as vezes é chato essas perguntas mas....
> > > sua classe ThreadManager.py esta funcionando corretamente para pausar os thread? vi q esta implementada mas no meu código não funcionou corretamente para "Pausar" os thread em execução mesmo seguindo o guia de comentário.
> > > Se puder dar uma ajuda, ate compartilho o projeto, como estou "Brincando" com o python por hobby, esta dificil compreender o codigo haha ( programação por hobbie msm)
> > > "PrintScreen" é o método responsável por tirar print da tela
> > > ![ae](https://user-images.githubusercontent.com/34078319/116941957-07e47400-ac47-11eb-88b3-122659a4ebf9.png)
> > 
> > 
> > Amigo você fazer um fork pra o linux, pode compartilhar comigo? Abraços!
> 
> Posso te passar o projeto base, mas o fork não vai funcionar pq meu projeto está bem diferente..
> Ainda n tem nada funcionando.. meu filho nasceu e n tô com tempo.. fiz só as classes de interação com Tibia(use, look, open, goto, etc), pegar layout do jogo, mas nada automatizado ainda... Depois vou te mandar privado

Opa, amigão passa no meu email... tá no meu perfil
