### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MahmoudAshrafMahmoud** [MuriloChianfa/TibiaAuto12#67]
Hey there,

I'd like to report that it does crash the pc after running it for 15-60 m i think it does not release memory properly so it actually makes the pc suddenly start acting so slow that it can be considered not responsive at all

**Comment by MuriloChianfa** [comment]
hummm, I’ll take a look to see what’s going on

**Comment by MahmoudAshrafMahmoud** [comment]
I think I got the hang of it its some kind of exceptions outside the scope of  Tibia auto but its caused by it , I think you have to check the foreground application before executing any action (Make sure Tibia Client is the Active one), I noticed the crash always happening when the GPU makes the screen blank and starts rendering again, like when you plug another monitor or run another application that works in full screen, sadly though these are not the only scenarios as I noticed it happen many times when I start the TA (Maybe Something is wrong with the configuration about the display, maybe something changed since the last time I ran so I think you need to auto configure each time or at least validate if the config you read is okay, then we come to see that every time config is better XD ). I am thinking about using your code and converting it to C# as I am a dot net dev but idk if this is going to be efficient, please tell if you see disadvantages or dead ends

**Comment by MuriloChianfa** [comment]
I don't see any disadvantage in rewriting in C#, I think it would be cool = D

**Comment by MahmoudAshrafMahmoud** [comment]
![image](https://user-images.githubusercontent.com/27304773/118888618-2d86a400-b8fc-11eb-8733-43fc66eb2fda.png)
