### ISSUE TITLE
Estou com um problema

### ISSUE THREAD

**Issue by chewbaccarr** [MuriloChianfa/TibiaAuto12#7]
Esta dando isso:
X GAME WINDOW ERROR
Setting window size...

**Comment by MuriloChianfa** [comment]
Boa tarde, o que pode estar dando problema, é de que ele não esteja achando esta imagem: ![image-title](https://i.imgur.com/LBbxT7k.png) , vou tentar fazer alguns ajustes, pois bastante gente esta tendo problemas com isso, desde já agradeço.

**Comment by miguelshta21** [comment]
bom dia eu quero correr isso em linux
