### ISSUE TITLE
Bypassing Battleye

### ISSUE THREAD

**Issue by ScriptCopyPaster** [MuriloChianfa/TibiaAuto12#74]
Thank you for your amazing work done!

I'm a programming student and I'm experimenting with python. 

What is the exact module that bypasses battleye with OBS? 
I'm trying to improve isolate the cavebot and improve the attacking. 

Thanks in advance!

**Comment by MuriloChianfa** [comment]
OBS itself ignores tibia's black screen, we imagine it's some kind of signature to capture whitelist
