### ISSUE TITLE
cavebot

### ISSUE THREAD

**Issue by wemersonpereira** [MuriloChianfa/TibiaAuto12#76]
Estou tentando configurar pela primeira vez o cavebot, porém sempre dá esse erro de não localizado
![image](https://user-images.githubusercontent.com/39955615/141676609-4b6ab6b8-f140-4083-b64c-d2aaaa7c3db6.png)
alguém sabe o motivo disso? pode me ajudar?

**Comment by MuriloChianfa** [comment]
você está com o monitor do tibia como principal ?

tente trocar o zoom do minimapa pra ver funciona também

**Comment by kyugin1** [comment]
murilo obrigado por todo conteudo seria interessante fazer um explicativo a mais do cavebot
