### ISSUE TITLE
Your configure status: False

### ISSUE THREAD

**Issue by fcarlessi** [MuriloChianfa/TibiaAuto12#78]
Boa noite, fiz todos os passos corretamente, demorei mas fiz e mesmo assim aparece isso quando inicio:
![image](https://user-images.githubusercontent.com/95160100/143732039-5d24cad7-e271-42ee-89a1-9e4e9a050999.png)

alguem pode me ajudar? `-`

**Comment by fcarlessi** [comment]
fiz tambem todo este turorial: http://www.qarevolution.com/learn-how-to-setup-selenium-with-eclipse-and-python/
so nao instalei o selenium, seria este o problema?

**Comment by fcarlessi** [comment]
N'ao consigo fazer o bot iniciar de maneira alguma, sera que alguem poderia me ajudar? por team viewer ou algo do tipo? 
Desculpem o incomodo :/

Discord: Carlessi#2985

**Comment by MuriloChianfa** [comment]
nessa parte, ele copia a configuração padrão para poder adjustar com a sua

tem permissão de escrita na pasta ? você também pode tentar rodar ele como administrador

se nada der certo, tenta copiar ele manualmente pra pasta Scripts, este é o meu:

nome: NewConfig.json

`{
    "Stats": true,
    "MouseOption": 0,
    "ItemsMode": "Frames",
    "Paths": {
        "MainPath": "images",
        "ItemsPath": "images/Items/Frames/",
        "ChestsPath": "images/Depot/Chests/",
        "ContainersNamePath": "images/Items/ContainersName/",
        "CavebotScriptsPath": "Scripts/"
    },
    "Positions": {
        "LifePosition": [
            {
                "x": 1758,
                "y": 124,
                "Stats": true
            }
        ],
        "ManaPosition": [
            {
                "x": 1759,
                "y": 137,
                "Stats": true
            }
        ],
        "BattlePosition": [
            {
                "x": 1580,
                "y": 3,
                "Stats": true
            }
        ],
        "PlayerPosition": [
            {
                "x": 871,
                "y": 429,
                "Stats": true
            }
        ]
    },
    "Boxes": {
        "StatusBarBox": [
            {
                "x": 1753,
                "y": 292,
                "w": 1858,
                "h": 302,
                "Stats": true
            }
        ],
        "BattleBox": [
            {
                "x": 1580,
                "y": 3,
                "w": 1727,
                "h": 418,
                "Stats": true
            }
        ],
        "RingBox": [
            {
                "x": 1753,
                "y": 234,
                "w": 1784,
                "h": 265,
                "Stats": true
            }
        ],
        "AmuletBox": [
            {
                "x": 1753,
                "y": 162,
                "w": 1784,
                "h": 193,
                "Stats": true
            }
        ],
        "GameWindowBox": [
            {
                "x": 174,
                "y": 2,
                "w": 1568,
                "h": 857,
                "Stats": true
            }
        ],
        "MapBox": [
            {
                "x": 1753,
                "y": 5,
                "w": 1858,
                "h": 113,
                "Stats": true
            }
        ]
    },
    "SQM": {
        "SQM1": [
            {
                "x": 779,
                "y": 506,
                "Stats": true
            }
        ],
        "SQM2": [
            {
                "x": 871,
                "y": 506,
                "Stats": true
            }
        ],
        "SQM3": [
            {
                "x": 963,
                "y": 506,
                "Stats": true
            }
        ],
        "SQM4": [
            {
                "x": 779,
                "y": 429,
                "Stats": true
            }
        ],
        "SQM5": [
            {
                "x": 871,
                "y": 429,
                "Stats": true
            }
        ],
        "SQM6": [
            {
                "x": 963,
                "y": 429,
                "Stats": true
            }
        ],
        "SQM7": [
            {
                "x": 779,
                "y": 352,
                "Stats": true
            }
        ],
        "SQM8": [
            {
                "x": 871,
                "y": 352,
                "Stats": true
            }
        ],
        "SQM9": [
            {
                "x": 963,
                "y": 352,
                "Stats": true
            }
        ]
    }
}`
