### ISSUE TITLE
this is not

### ISSUE THREAD

**Issue by miguelshta21** [MuriloChianfa/TibiaAuto12#8]
eu quero usar ele em linux consege me ajudar?

**Comment by MuriloChianfa** [comment]
Bom dia amigo, ainda não testei ele no linux, provavelmente, algumas bibliotecas não seriam compatíveis, eu posso dar uma olhada depois pra ver o que eu consigo fazer... qualquer coisa lhe dou um retorno. Vlw Abraços.

**Comment by miguelshta21** [comment]
tem alguma forma de manter contato com vc?

**Comment by MuriloChianfa** [comment]
Agora eu estou usando o Discord... Meu ID para você me adicionar é: Light#1555

**Comment by miguelshta21** [comment]
ja adicione bro

**Comment by miguelshta21** [comment]
nao consigo contatar com vc

**Comment by MuriloChianfa** [comment]
Só agora que eu vi >.<, desculpe-me, respondi lá.
