### ISSUE TITLE
Usar sem OBS

### ISSUE THREAD

**Issue by carlosrcjunior** [MuriloChianfa/TibiaAuto12#80]
Tem alguma forme de usar o BOT sem o OBS? 
Gostaria de usar em OT

**Comment by MuriloChianfa** [comment]
Tem, acabei de tirar a dependência do OBS, agora dá pra escolher e janela em específico.

**Comment by chikoria** [comment]
> Tem, acabei de tirar a dependência do OBS, agora dá pra escolher e janela em específico.

No global só com OBS?

**Comment by MuriloChianfa** [comment]
boa tarde, no global ainda só com OBS, por conta do bloqueio da tela do tibia.
