### ISSUE TITLE
bot abre e fecha

### ISSUE THREAD

**Issue by magriNbh** [MuriloChianfa/TibiaAuto12#81]
ja instalei as libs necessárias, porem quando instalo o networkx ele da erro, mas ao digitar python -m pip list , o networkx aparece na lista. 

Enfim, quando clico no main ele abre e fecha bem rápido, sabe o que pode ser ? estou usando a última versão do python

**Comment by MuriloChianfa** [comment]
voce pode tentar abrir pelo terminal

como eu abro o BOT:

![image](https://user-images.githubusercontent.com/60560085/166604997-7ba17c57-5bf8-4b68-a3e5-370dc7d7d051.png)

**Comment by MuriloChianfa** [comment]
vou colocar no roadmap uma opção pra poder abri-lo como um executavel ou até mesmo um PE
