### ISSUE TITLE
Error[1] = BattllePosition

### ISSUE THREAD

**Issue by ftlsxp** [MuriloChianfa/TibiaAuto12#85]
Oi, tudo bem?

Nao importa o que eu faça, fica dando esse erro  na configuraçao.

Some Errors Occurred... Opening The Manual Config.
Unfortunately, You Will Have To Manually Configure The Following Errors:

Error[1] = BattlePosition

Consegue me ajudar, por favor?

Obrigado.

![image](https://user-images.githubusercontent.com/105999605/169677439-1b5d9971-ecdc-46a2-99ea-1f15896435a5.png)

**Comment by MuriloChianfa** [comment]
pra abrir o BOT, você precisa estar com o battle aberto, pra ele pegar a posição na tela.

**Comment by ftlsxp** [comment]
Mas ele tá aberto. Tá ali no print. Você sabe se deu alguma mudança no OBS? Pergunto porque eu tentei fazer uns macros com autohotkey, mas a função de findimage não consegue ler a tela do obs. Tô tendo resultados bem aleatórios no seu. Na maioria das vezes fica num loop tentando achar a posição do player. Nas outras vezes não encontra um monte de coisa, fica tudo dando zero. Teve so uma vez que funcionou, mas ele ficou clicando fora do cliente do tibia. Será que tem a ver com o fato do meu monitor ser ultra wide? De qualquer maneira, parabéns pelo trabalho e obrigado por compartilhar e se dispor a ajudar. Abraços

**Comment by MuriloChianfa** [comment]
humn, eu não tinha visto que o battle está aberto mesmo... mas talvez possa ser a resolução do monitor mesmo

**Comment by marciowinicius** [comment]
@ftlsxp tenta mudar a configuração de saida do tibia no OBS ... Vai lá em configurações do OBS, vai em vídeo e a configuração de saida vc diminui um pouco ... talvez seu monitor seja mt grande e ele n ta conseguindo detectar tudo certinho. Eu fiz aqui e deu certo aparentemente.

**Comment by ftlsxp** [comment]
Beleza, pessoal. Vou experimentar aqui e aviso se descobrir algo. Obrigado. Abraços
