### ISSUE TITLE
cave bot successfully Located The Mark: {  CheckMark  } Clicking On Your Position Didn't Arrived At Mark: CheckMark

### ISSUE THREAD

**Issue by kyugin1** [MuriloChianfa/TibiaAuto12#86]
ele localiza aonde esta o ponto de marcacao mas o segue , queria saber se tem alguma dica do que pode ser agradeco desde ja 
![imagem_2022-06-03_174138867](https://user-images.githubusercontent.com/105323208/171949210-c6280be2-9612-4c9f-819d-c1ded4b6c3c3.png)

**Comment by MuriloChianfa** [comment]
você está com 3 checkpoints iguais no mapa, talvez deixar somente 1 ajude.

**Comment by kyugin1** [comment]
coloquei pontos diferentes mas do msm jeito , ele buga 
![image](https://user-images.githubusercontent.com/105323208/172065801-e504ef33-0e1a-4d4e-bc66-979010f88dab.png)

**Comment by MuriloChianfa** [comment]
parece que ele não está conseguindo clicar no mapa, tenta mudar o zoom pra ver se ele clica.

**Comment by kyugin1** [comment]
tentei todos os zooms do mapa mas parece que nao esta funcionando msm, sera q pode ser problema de resolucao ou na cfg do obs?

**Comment by MuriloChianfa** [comment]
pode ser a config mesmo, dela não encontrar o minimapa direito, fico no arquivo de confi na pasta scripts:

![image](https://user-images.githubusercontent.com/60560085/172067003-d592c845-a996-45a8-8f9f-2e96d2c10492.png)

dá uma olhada na sua pra ver se está certo.

**Comment by kyugin1** [comment]
sou novato, nao sei se entrei no arquivo certo , poderia dar uma olhada. se for o certo nao tem nada escrito do mapbox 
![image](https://user-images.githubusercontent.com/105323208/172069441-cc264467-1490-4a5f-8db2-f81f111bdfca.png)

**Comment by kyugin1** [comment]
creio que o unico q mostra algo sobre mini map e no comeco quando abri o bot 
![image](https://user-images.githubusercontent.com/105323208/172069520-b555c4f9-16f2-4275-b88c-330ed37f1f7c.png)

**Comment by MuriloChianfa** [comment]
aparentemente, ele pegou certo a posição do mapa, talvez seja algo no programa mesmo.

**Comment by kyugin1** [comment]
ta certo entao, obrigado

**Comment by kyugin1** [comment]
esqueci de avisar mas consegui funcionar , agradeco a atencao

**Comment by DouglasSMartins** [comment]
Salve, como você resolveu @kyugin1 , aqui estou com o mesmo problema e não consigo resolver.
