### ISSUE TITLE
Reconfiguring The Player Position (error need help)

### ISSUE THREAD

**Issue by CarstenPaulo** [MuriloChianfa/TibiaAuto12#88]
rodei o projeto aqui, mas não está pegando a posição do player - fica mostrando (recofiguring the player position), já inseri as posições que tu solicitou na descrição do projeto e também tentei colocando as posição usando o pyautogui usando o displaymouseposition e nada
preciso de ajuda, vlw
e parabéns pelo projeto!

![image](https://user-images.githubusercontent.com/60640750/172217959-efe171af-303d-4ade-a9d8-6a76fee120e5.png)

**Comment by MuriloChianfa** [comment]
se você configurou manualmente, tem que setar no config.json o configured como true, pra ele entender que não precisa tentar configurar:

![image](https://user-images.githubusercontent.com/60560085/172497293-c084baaf-9f84-4fcc-af92-3424b88aac3a.png)

**Comment by CarstenPaulo** [comment]
opa, obrigado por responder 
dai ele nao precisa configurar e quando eu abro o bot eu clico em load up eh isso?
![image](https://user-images.githubusercontent.com/60640750/172504216-3961d7b5-c6a4-4be2-9b1c-4ae6458153c1.png)
e o bot fica assim, com algumas funcionalidades bloqueadas?

**Comment by CarstenPaulo** [comment]
dai abre o bot assim com algumas funcionalidades bloqueadas, ta certo?
