### ISSUE TITLE
Preciso De Ajuda Com o PIP

### ISSUE THREAD

**Issue by thunszather** [MuriloChianfa/TibiaAuto12#9]
boa noite, baixei agora o seu bot e achei muito bom so que nao consigo instalar essas coisas no py fala que o pip nao é executavel, sabe q qeu faço?

**Comment by MuriloChianfa** [comment]
opa amigo, posso ajudar sim... esse "pip", voce pode executar ele de 2 formas, a mais facil, na minha visao, é localizar ele na pasta do python e executar pelo terminal... espera ai que eu vou tirar algumas prints aqui.

**Comment by MuriloChianfa** [comment]
você tem que localizar a pasta de instalação do seu python primeiro, a minha por exemplo esta aqui:

![Alt text](https://i.imgur.com/DDK1lhQ.png)

depois você entra na pasta Scripts e copia o caminho dela:

![Alt text](https://i.imgur.com/fe6nZka.png)

agora voce abre o terminal e digita: cd [e cola o caminho que voce copio]

![Alt text](https://i.imgur.com/ByBY88f.png)

depois é só executar os comandos do pip pra instalar as bibliotecas necessaria:

![Alt text](https://i.imgur.com/OqCvgEZ.png)

**Comment by thunszather** [comment]
caralhoooo era isso mesmo, sofaltava achar a pasta no appdata, vou tentar instalar os negocios agora, obrigado pela atençao mano! vc e foda de conseguir desenvolver isso parabens!!! ja volto

**Comment by thunszather** [comment]
ae consegui instalar todos os pips, mas uma unica duvida é o executavel startbot que nao estou achando 
![image](https://user-images.githubusercontent.com/67078429/84957970-bb498600-b0d2-11ea-864a-24dee99515df.png)

**Comment by MuriloChianfa** [comment]
Infelizmente, o BOT ainda está trabalhando com o OBS mas em breve vou tentar resolver isso, porem.

Pra iniciar o BOT, você precisa estar com o OBS aberto e clicar no arquivo "Main.py" que ele já vai abrir.

**Comment by thunszather** [comment]
ah eu consegui tudo direitinho mas deu esse erro 
![image](https://user-images.githubusercontent.com/67078429/84958478-d36dd500-b0d3-11ea-9f12-0bd5335ea62a.png)

**Comment by thunszather** [comment]
CONSEGUI!!!!!!!!!!!!!!!!!!! TE AMO MT OBRIGADO PELO BOT E MEUS PARABENS DE NOVO VOU TESTAR TUDO AGORA VLWWWW

**Comment by thunszather** [comment]
![image](https://user-images.githubusercontent.com/67078429/84960062-141b1d80-b0d7-11ea-988d-fd3e6896db87.png)

**Comment by MuriloChianfa** [comment]
Editei seu print, porque estava aparecendo o nome do personagem kkkkkk, as vezes se alguém reportar da problema...

Mas é isso ai, testa tudo certinho, e o que você achar que precisa melhorar é só falar. Vlw abraços.

**Comment by MuriloChianfa** [comment]
Só uma dica, aquele erro que você postou ali em cima, é porque ele não conseguiu achar as posições da barra de mana, provavelmente porque o seu OBS não estava reproduzindo o tibia em tela cheia, pra ele ficar certinho, ele precisa estar idêntico ao tibia.

**Comment by thunszather** [comment]
Foi isso mesmo mano, o bot funciona perfeitamente, parabens mais uma vez a voce!! estou jogando em  otserver e ta tudo normal, so uma perguntinha a mais, pra trocar o bixo no cavebot, eu mudo dentro do StoneRefinerVenore o nome dos bixos? obrigado! vc e mt atencioso tb, e vc podia fazer um video pra explicar igual disse no comentario do youtube, iria ajudar muita gente, eu achei o seu site aki de um modo mt aleatorio, surpreendente!

**Comment by MuriloChianfa** [comment]
Opa... obrigado amigo, fico feliz pelo seu feedback também.

Pra adicionar novos monstros pra atackar, você precisa entrar na pasta "conf" e abrir o arquivo "Constants.py"... lá você vai procurar por "Monsters" dai vai estar alguns nomes que eu deixei de exemplo, dai é só você colocar o nome que quiser... depois de colocar o nome lá, você precisa tirar uma print do monstro e coloca na pasta "Target", em "imagens" (o nome da imagem tem que ser o mesmo nome que você colocou no arquivo Constants.py).

Dai é só reiniciar o BOT e pronto já vai aparecer lá pra você testar.

**Comment by MarceloShibutani** [comment]
estou com problemas nas intalacoes tambem 
![image](https://user-images.githubusercontent.com/131549449/233817274-815c9b5c-641a-4ee1-8036-487e0614d1a2.png)
