### ISSUE TITLE
Travando ao iniciar

### ISSUE THREAD

**Issue by Kristofer1212** [MuriloChianfa/TibiaAuto12#91]
Olá, o bot esta travando ao iniciar, depois de clicar em Create, ele fica um tempo travado em Copiando Json, ai meio que abre uma miniaturazinha do bot em uma janela pequena preta, e aparece nao respondendo. Como posso proceder ? Desde já, obrigado

**Comment by MuriloChianfa** [comment]
provável que esteja travando nessa parte:

![image](https://user-images.githubusercontent.com/60560085/173157996-8ba10f06-2c73-42cb-8501-16a0d8f511b6.png)

Pra arrumar, você pode copiar manualmente o script padrão pro novo, na pasta "scripts"... só copiar o "Json.json" e renomear o novo arquivo pra "NewConfig.json", que é o nome padrão da configuração.
