### ISSUE TITLE
[BUG] Offset da imagem não considerando a toolbar

### ISSUE THREAD

**Issue by augustocrmattos** [MuriloChianfa/TibiaAuto12#93]
Eu baixei no meu computador para testar e debugar o código e detectei que na hora de trazer as coordenadas o meu cv2 está pegando da imagem sem contar a barra superior do aplicativo (que tem o minimizar, sair etc.), deixando tudo com um offset em Y de -23 pixels, o que está fazendo ele clicar errado. Não manjo muito do cv2 nem do HookWindow ainda que você criou, e não consegui pensar numa forma elegante de encontrar esse offset dinamicamente, então achei melhor abrir um bug aqui.

PS: Sigo tentando achar uma solução aqui eu mesmo, mas não sou Dev então sofro um pouco.
![Screenshot_1](https://user-images.githubusercontent.com/32346329/175538968-7c657d01-0b7b-4abb-a362-9944b0600cf2.png)
![Screenshot_2](https://user-images.githubusercontent.com/32346329/175538981-49c998b0-51b2-4173-b70c-1b0feb725f03.png)

**Comment by augustocrmattos** [comment]
Meu erro, isso já está considerado. O problema para o offset tem que estar em outro lugar, pois por exemplo o meu código está sempre só conseguindo selecionar o segundo monstro no battle, pois por algum motivo o mouse gera um offset que impede a maioria das funções. Ele não está curando sozinho também e acho que é porque está defasado e printando o local errado, vou debugar mais e depois abrir outra issue.

**Comment by MuriloChianfa** [comment]
dependendo da opção de mouse que você escolheu, ele atribui +24 px no eixo Y justamente por conta da toolbar da jabela:

![image](https://user-images.githubusercontent.com/60560085/175570073-45b6764a-edb9-4ed4-a00e-fc8f71138b92.png)

MoveMouse: https://github.com/MuriloChianfa/TibiaAuto12/blob/02619320f03a6d5bd30623f73056d8714276043e/core/MoveMouse.py#L53
SendToClient: https://github.com/MuriloChianfa/TibiaAuto12/blob/02619320f03a6d5bd30623f73056d8714276043e/core/SendToClient.py#L105
