### ISSUE TITLE
[BUG] Coordenadas X com offset incorreto

### ISSUE THREAD

**Issue by augustocrmattos** [MuriloChianfa/TibiaAuto12#94]
Boa tarde,

Refiz alguns testes, debuguei durante o dia todo, inclusive até tentei mudar a referência para absoluta no código, mas não consegui entender o motivo do meu Bot ter um offset fixo no eixo X. Evidências abaixo:

Essa imagem mostra as coordenadas no código que ele está passando para o mouse_event (1438,22 está correto). Isso é para detectar o ícone no mapa)
![Screenshot_5](https://user-images.githubusercontent.com/32346329/175666854-314ec4fe-d387-4e94-afe3-eb31a7616568.png)

Nessa imagem evidenciei a coordenada exata do ícone (meu mouse não aparece mas está aí)
![Screenshot_4](https://user-images.githubusercontent.com/32346329/175666981-5fe15546-4935-4547-83d7-3b733f2b5c0d.png)

E essa é a posição em que o mouse pula quando a linha de evento é executada
![Screenshot_3](https://user-images.githubusercontent.com/32346329/175667062-eca6c28a-bb50-481d-8283-44213c883180.png)

Por algum motivo ele não vai para a posição correta, mesmo o mouse_event recebendo os parâmetros certos.

Fiz algumas análises:

Mudei o MoveTo para essa:
`    def MoveTo(self, x, y):
        old_pos = self.get_position()
        x = x if (x != -1) else old_pos[0]
        y = y if (y != -1) else old_pos[1]
        self._do_event(self.MOUSEEVENTF_MOVE + self.MOUSEEVENTF_ABSOLUTE, x, y+24, 0, 0)`

LeftClick:
`    def LeftClick(self, Position):
        print(f"Left Click X {Position[0]} Y: {Position[1]+24}")
        self.MoveTo(Position[0], Position[1] + 24)
        self._do_event(self.MOUSEEVENTF_LEFTDOWN + self.MOUSEEVENTF_LEFTUP, 0, 0, 0, 0)`

E o método _do_event:
`    def _do_event(self, flags, x_pos, y_pos, data, extra_info):
        """generate a mouse event"""
        print(ctypes.windll.user32.GetSystemMetrics(self.SM_CXSCREEN))
        print(ctypes.windll.user32.GetSystemMetrics(self.SM_CYSCREEN))
        x_calc = 65536 * x_pos / ctypes.windll.user32.GetSystemMetrics(self.SM_CXSCREEN) + 1
        y_calc = 65536 * y_pos / ctypes.windll.user32.GetSystemMetrics(self.SM_CYSCREEN) + 1
        return self.DLL.mouse_event(flags, int(x_calc), int(y_calc), data, extra_info)`

Acreditei que usando referências absolutas eu talvez tivesse sucesso, mas o offset segue em frente.

Tentei esse cara também:
`ctypes.windll.shcore.SetProcessDpiAwareness(0)`

Porém nada... Alguma ideia? Não vou desistir aqui, mas as vezes você sabe algo que possa tentar.

As imagens feitas foram no código da master mesmo, sem alterações, porém com as alterações dá na mesma. Acho que pode ser algum setup que tenha que ser parametrizado já que o código está enviando corretamente as coordenadas.

Só possuo um monitor, é notebook (1920x1080) executei comandos para o python pegar as coordenadas do PC, detectou com sucesso.
`print(ctypes.windll.user32.GetSystemMetrics(self.SM_CXSCREEN))
        print(ctypes.windll.user32.GetSystemMetrics(self.SM_CYSCREEN))`

**Comment by augustocrmattos** [comment]
Rodei esse teste abaixo, e com ele a coordenada é aplicada corretamente. Só o que resta é em algum momento existir uma configuração no seu código que cause diferença:

```
import ctypes
import ctypes.wintypes
import win32api
import time

MOUSEEVENTF_MOVE = 0x0001 # mouse move
MOUSEEVENTF_LEFTDOWN = 0x0002 # left button down
MOUSEEVENTF_LEFTUP = 0x0004 # left button up
MOUSEEVENTF_RIGHTDOWN = 0x0008 # right button down
MOUSEEVENTF_RIGHTUP = 0x0010 # right button up
MOUSEEVENTF_MIDDLEDOWN = 0x0020 # middle button down
MOUSEEVENTF_MIDDLEUP = 0x0040 # middle button up
MOUSEEVENTF_WHEEL = 0x0800 # wheel button rolled
MOUSEEVENTF_ABSOLUTE = 0x8000 # absolute move
SM_CXSCREEN = 0
SM_CYSCREEN = 1


def _do_event(flags, x_pos, y_pos, data, extra_info):
    x_calc = 65536 * x_pos / ctypes.windll.user32.GetSystemMetrics(SM_CXSCREEN) + 1
    y_calc = 65536 * y_pos / ctypes.windll.user32.GetSystemMetrics(SM_CYSCREEN) + 1
    return ctypes.windll.user32.mouse_event(flags, int(x_calc), int(y_calc), data, extra_info)

def move_mouse(pos):
        (x, y) = pos
        old_pos = get_position()
        x =  x if (x != -1) else old_pos[0]
        y =  y if (y != -1) else old_pos[1]
        _do_event(MOUSEEVENTF_MOVE + MOUSEEVENTF_ABSOLUTE, x, y, 0, 0)

def get_position():
        return win32api.GetCursorPos()

def teste():

    while 1 > 0:
        h_x, h_y = get_position()
        print(f"X {h_x} Y {h_y}")
        pos = (1438,46)
        move_mouse(pos)
        time.sleep(2)


if __name__ == '__main__':
    teste()
```


Resultado do teste:
![image](https://user-images.githubusercontent.com/32346329/175691970-a9da8bad-4db2-4592-a8f6-579825c7bae3.png)

**Comment by DouglasSMartins** [comment]
Boa tarde/noite,

Eu ando fazendo alguns testes também, porem bem longe desse nível que você está.

Eu consegui usar o cavebot usando ele no modo global, onde ele usa o sendtoclient, dessa forma ele consegui clicar e andar corretamente, porem usando o modo de ot, que acredito eu seja isso que você está testando, eu tenho também problemas, no meu caso ele anda pra cima do ponto. Vou anexar uma imagem de exemplo, ao inves de ele ir para o X da imagem, ele vai mais pra cima.

![andar](https://user-images.githubusercontent.com/21184059/175695623-b946c783-ef2b-486f-aaa3-3657ebb981b9.png)

Esse teste que você fez que diz ter dado certo, é em qual arquivo? gostaria de testar aqui também pra ver se consigo agregar em algo.

**Comment by augustocrmattos** [comment]
Boa noite,

Pior que estou rodando no Global mesmo, conforme imagem (redimensionei pra ficar mais fácil de ver os textos, ignora as texturas):
![image](https://user-images.githubusercontent.com/32346329/175696670-c088cd2c-9a74-4f2f-8edd-d84143e5cc69.png)

O teste que eu fiz foi num código separado só meu e eu coloquei ele todo aí já no segundo comentário, porém quando eu jogo esse código funcional no bot, ele não retorna as coordenadas corretas.

DETALHE: Eu estou vinculando o Window Hook para o Tibia e não para o OBS, não sei se isso pode ter um impacto.

**Comment by augustocrmattos** [comment]
Fiz novo teste agora vinculando a tela do OBS, mesmo problema com os dois códigos.

**Comment by MuriloChianfa** [comment]
tenta usar a outra opção, a de send mouse events, ou dá pra tentar também, adicionar +24 px no Y, em todas as capturas do HookWindow

**Comment by augustocrmattos** [comment]
Solução "encontrada". Parece que por algum motivo meu monitor talvez esteja coloca um _aspect ratio_ diferente. Percebi que se eu mando x=100 e y=100, ele coloca o mouse em 80,80. Fiz as contas e vi que é linear, ou seja, basta multiplicar a coordenada por 1,25 e sucesso:
![image](https://user-images.githubusercontent.com/32346329/175703540-fc82b572-68d7-466a-b03c-45067f54cc47.png)

![image](https://user-images.githubusercontent.com/32346329/175703973-31b59707-8524-40e0-b2e1-a26b4cfbe9b3.png)

Particularmente eu acho que é mais um HACK que qualquer coisa, porém acho que agora o ponto é entender o motivo dessa variação e como podemos adaptar e mitigar.

Essa ação é na movimentação do mouse e não tem relação com a aquisição de coordenadas dos Hooks, então creio que seja algo particular da biblioteca ou coisa assim.

**Comment by augustocrmattos** [comment]
Criei duas constantes locais:

```
self.TOOLBAR_CONST = 30
self.ASPECT_RATIO_OFFSET = 1.25
```

E adicionei as regras baseadas nela. Vou testar agora para ver, depois descobrir o motivo dessa divergência. Se isso for uma característica do ambiente, talvez colocar uma selection box para dar o poder para o usuário selecionar.

PS: Foi necessário multiplicar 24 do offset do toolbox por 1,25 também, resultando em 30.

```
    def LeftClick(self, Position):
        Position[0] = Position[0]*self.ASPECT_RATIO_OFFSET
        Position[1] = Position[1] * self.ASPECT_RATIO_OFFSET
        self.DLL.SetCursorPos(Position[0], Position[1] + self.TOOLBAR_CONST)
        self.DLL.mouse_event(self.MOUSEEVENTF_LEFTCLICK, ctypes.c_long(Position[0]), ctypes.c_long(Position[1] + self.TOOLBAR_CONST), 0, 0)

    def RightClick(self, Position):
        Position[0] = Position[0] * self.ASPECT_RATIO_OFFSET
        Position[1] = Position[1] * self.ASPECT_RATIO_OFFSET
        self.DLL.SetCursorPos(Position[0], Position[1] + self.TOOLBAR_CONST)
        self.DLL.mouse_event(self.MOUSEEVENTF_RIGHTCLICK, ctypes.c_long(Position[0]), ctypes.c_long(Position[1] + self.TOOLBAR_CONST), 0, 0)

    def MoveTo(self, X, Y):
        X = X * self.ASPECT_RATIO_OFFSET
        Y = Y * self.ASPECT_RATIO_OFFSET
        self.DLL.SetCursorPos(X, Y + self.TOOLBAR_CONST)

    def DragTo(self, From, To):
        From[0] = From[0] * self.ASPECT_RATIO_OFFSET
        From[1] = From[1] * self.ASPECT_RATIO_OFFSET
        To[0] = To[0] * self.ASPECT_RATIO_OFFSET
        To[1] = To[1] * self.ASPECT_RATIO_OFFSET
        self.DLL.SetCursorPos(From[0], From[1])
        self.DLL.mouse_event(self.MOUSEEVENTF_LEFTDOWN, ctypes.c_long(From[0]), ctypes.c_long(From[1] + self.TOOLBAR_CONST), 0, 0)
        self.DLL.SetCursorPos(To[0], To[1] + self.TOOLBAR_CONST)
        self.DLL.mouse_event(self.MOUSEEVENTF_LEFTUP, ctypes.c_long(To[0]), ctypes.c_long(To[1] + self.TOOLBAR_CONST), 0, 0)

    def UseOn(self, From, To):
        From[0] = From[0] * self.ASPECT_RATIO_OFFSET
        From[1] = From[1] * self.ASPECT_RATIO_OFFSET
        To[0] = To[0] * self.ASPECT_RATIO_OFFSET
        To[1] = To[1] * self.ASPECT_RATIO_OFFSET
        self.DLL.SetCursorPos(From[0], From[1] + self.TOOLBAR_CONST)
        self.DLL.mouse_event(self.MOUSEEVENTF_RIGHTDOWN, ctypes.c_long(From[0]), ctypes.c_long(From[1] + self.TOOLBAR_CONST), 0, 0)
        self.DLL.mouse_event(self.MOUSEEVENTF_RIGHTUP, ctypes.c_long(From[0]), ctypes.c_long(From[1] + self.TOOLBAR_CONST), 0, 0)
        self.DLL.SetCursorPos(To[0], To[1] + self.TOOLBAR_CONST)
        self.DLL.mouse_event(self.MOUSEEVENTF_LEFTDOWN, ctypes.c_long(To[0]), ctypes.c_long(To[1] + self.TOOLBAR_CONST), 0, 0)
        self.DLL.mouse_event(self.MOUSEEVENTF_LEFTUP, ctypes.c_long(To[0]), ctypes.c_long(To[1] + self.TOOLBAR_CONST), 0, 0)
```

**Comment by DouglasSMartins** [comment]
Você usa o mesmo que eu então, creio que seja algo de ambiente, pois pra mim usando como global ele funciona sem problemas a parte de andar pelos pontos, só não funciona caso use como OT, ai acontece conforme falei acima.

Uma das coisas que mais atrapalha, e que é algo já conhecido pelo próprio @MuriloChianfa é o lance do target, ele fica mudando sem parar, não fica com um target até ele morrer, ele da 1-2 hits e tira o target, ai coloca de novo. 
Isso é bem ruim, pois se vai em uma hunt mais forte, o q te mantem vivo é o combo da cura com o vampirismo dos itens, e com ele tirando o target, perde alguns turnos cruciais.

Não ta afim de dar uma testada e ver se tu consegue uma solução pra essa parte? Eu to tentando, fazendo testes, mas não consegui resolver nada ainda.
