### ISSUE TITLE
Trava em Reconfiguring The Player Position

### ISSUE THREAD

**Issue by brunobarroso13** [MuriloChianfa/TibiaAuto12#96]
Fiz a instalação, configurei o OBS e estou com as seguintes informações no terminal:

"
Your Configure Stats: False
Coping Default Json

Health Location [X: 0 Y: 0]

Mana Position Error
Battle Position Error

Status Bar Start [X: 0, Y: 0]
Status Bar End [X: 0, Y: 0]

Ring's Square Start [X: 0, Y: -58]
Ring's Square End [X: 31, Y: -27]

Amulet's Square Start [X: 0, Y: -130]
Amulet's Square End [X: 31, Y: -99]

MiniMap Start [X: -106, Y: 1]
MiniMap End [X: -1, Y: 109]

Size of MiniMap [X: 105, Y: 108]

Player Position [X: 0, Y: 0]

Game Window Start [X: 0, Y: 0]
Game Window End [X: 0, Y: 0]

Reconfiguring The Player Position

Reconfiguring The Player Position
"

Aí fica repetindo o "Reconfiguring The Player Position"

O que posso ter feito errado?

**Comment by DouglasSMartins** [comment]
Não precisa mais do OBS pra usar o bot, basta você abrir ele e selecionar a janela do seu tibia, talvez seja esse o problema.

**Comment by brunobarroso13** [comment]
Não funcionou, deu o mesmo erro.

Tô fazendo os seguintes passos:
I) Rodando o start.py pelo terminal (python start.py)
II) Ao abrir a janela executável, seleciono a janela do meu tibia (Tibia - nome do char)
III) Clico em Create, sem alterar nada
IV) O programa executa no terminal.
V) Algumas posições funcionam, outras não.

Seguem as posições que não são encontradas:
- Your Configure Stats: False

Mana Position Error
Battle Position Error

Status Bar Start [X: 0, Y: 0]
Status Bar End [X: 0, Y: 0]

Player Position [X: 0, Y: 0]

Game Window Start [X: 0, Y: 0]
Game Window End [X: 0, Y: 0]

Reconfiguring The Player Position

Aí fica repetindo o "Reconfiguring The Player Position" até eu forçar a parada com CTRL +C.

Ao forçar a parada, aparece a seguinte mensagem:

"Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.1
0_3.10.1520.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in
 __call__
    return self.func(*args)
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\module
s\ChooseConfig.py", line 72, in bootstrap
    bootstrap()
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\module
s\ChooseConfig.py", line 298, in bootstrap
    11], SQMs[12], SQMs[13], SQMs[14], SQMs[15], SQMs[16], SQMs[17] = Se
tSQMs()
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\G
etters.py", line 136, in SetSQMs
    SetSQMs()
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\G
etters.py", line 136, in SetSQMs
    SetSQMs()
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\G
etters.py", line 136, in SetSQMs
    SetSQMs()
  [Previous line repeated 269 more times]
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\G
etters.py", line 135, in SetSQMs
    3] = GetPlayerPosition()
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\G
etters.py", line 80, in GetPlayerPosition
    LeftGameWindow = LocateImage("images/PlayerSettings/LeftOption3.png"
, Precision=0.75)
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\H
ookWindow.py", line 120, in LocateImage
    TakedImage = TakeImage(Region)
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\H
ookWindow.py", line 91, in TakeImage
    TakedImage = Hooker().HookWindow()
KeyboardInterrupt"

**Comment by chikoria** [comment]
> Não precisa mais do OBS pra usar o bot, basta você abrir ele e selecionar a janela do seu tibia, talvez seja esse o problema.

Tem certeza? Que eu saiba tem um bloqueio de tela preta no tibia...

**Comment by MuriloChianfa** [comment]
no global ainda só com OBS, por conta do bloqueio da tela do tibia.

**Comment by MuriloChianfa** [comment]
@brunobarroso13 vê se o seu monitor está como principal caso tenha 2, ou tenta mudar sua resolução pra ver... a minha por exemplo é 1920x1024

**Comment by brunobarroso13** [comment]
Valeu, Murilo! Deu certo agora.

Quero fazer um script pra treinamento AFK nos Modified Gnarlhound. Onde encontro esses arquivos que já existem, pra ver se consigo editar e criar um de treino.

**Comment by brunobarroso13** [comment]
To com um problema na leitura da imagem do monstro que adicionei "Modified Gnarlhound"
Tem algo especial pra criar esse arquivo de imagem?
![ModifiedGnarlhound](https://user-images.githubusercontent.com/98397824/176539594-ad625202-84df-4885-95f0-ec8fa35abf8e.png)


Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inn
er
    self.run()
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\ThreadManager.py", line 107, in run
    self._target(SelectedThread)
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\ThreadManager.py", line 123, in Inner
    state = func(state)
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\ThreadManager.py", line 47, in HandleTarget
    _Target()
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\modules\CaveBot.py", line 73, in ScanCaveBot
    Controller.StartCaveBot(data, MonstersToAttack)
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\engine\CaveBot\CaveBotController.py", line 44, in StartCaveBot
    self.HandleCaveBot(data, i, MonstersToAttack)
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\engine\CaveBot\CaveBotController.py", line 114, in HandleCaveBot
    Number = NumberOfTargets(self.BattlePosition, Monster)
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\engine\CaveBot\Scanners.py", line 8, in NumberOfTargets
    Number = LocateAllImages('images/Targets/Names/' + Monster + '.png', Precision=0.8, Region=(
  File "C:\Users\Bruno Barroso\PycharmProjects\TibiaAuto12-master\core\HookWindow.py", line 180, in LocateAllImages
    res = cv2.matchTemplate(img_gray, template, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().hei
ght <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'

**Comment by MuriloChianfa** [comment]
o nome do arquivo tem que ser o mesmo que você colocou no arquivo de constantes

**Comment by brunobarroso13** [comment]
Ele encontra a imagem, mas a função matchTemplate da o seguinte erro:
Assertion failed) _img.size().hei
ght <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'

Por isso achei que poderia ser algo na imagem. A imagem precisa ser tirada do battle, certo?

**Comment by SolwynCa** [comment]
Estou tendo o mesmo problema, já tentei várias resoluções diferentes. O que posso fazer?

**Comment by brunobarroso13** [comment]
Pelo erro parece que a imagem está com altura e largura menor que a imagem do Template. Agora como fazer ela ficar igual a do Template eu ainda não descobri

**Comment by brunobarroso13** [comment]
Resolvi o problema da imagem, estava em 32bits, e o template é 24bits.

Agora ele acha o arquivo, quando inicio o CaveBot não gera erro mais, porém também não ataca o monstro.

Outro problema que não consegui ajustar ainda é sobre como movimentar a cada 15 minutos pra não deslogar. Tentei pelo Walker, mas não consegui fazer meu script com as marks funcionar. Ele fica andando igual doido, não fica parado pelo tempo que configuro.

Sabem se tem como apenas fazer alguma outra ação pra não deslogar?

**Comment by SolwynCa** [comment]
eu ainda estou agarrado no primeiro erro que vc mostrou aqui, como vc resolveu?

**Comment by brunobarroso13** [comment]
@SolwynCa minha tela estava diferente do exemplo do readme. Meu battle não estava na 2a janela lateral. Depois que deixei idêntico, funcionou.

Sobre o treino afk com os GnarlHound, consegui fazer funcionar usando apenas o auto hotkey.

OBS: o script só funciona se a tela do Tibia estiver em 1o plano né, então não tem como fazer outra coisa no PC enquanto o char treina. Mas tá ótimo já.
