### ISSUE TITLE
Some Errors Occurred... Opening The Manual Config.

### ISSUE THREAD

**Issue by Harery** [MuriloChianfa/TibiaAuto12#97]
![image](https://user-images.githubusercontent.com/33111142/177048922-f60c68cc-52c9-4412-9c3c-03e0973d036a.png)

**Comment by MuriloChianfa** [comment]
open your battle, maybe this could be it

**Comment by Harery** [comment]
> open your battle, maybe this could be it

thankyou its open now 
but with limited module 
![image](https://user-images.githubusercontent.com/33111142/177060236-952cd65a-a1c0-4627-8cb2-bb9a5d49750e.png)

**Comment by MuriloChianfa** [comment]
yeah its correct, not all modules are ready
